### ISSUE TITLE
Where to change section name color

### ISSUE THREAD

**Issue by AndsonYe** [posquit0/Awesome-CV#1]
Hi,

This is really a awesome CV template, I really like this one.

I am not very familiar with .cls and I spent a lot of time looking for the code defining the color of the first three characters of a section name. But I still cannot find it. Would you mind to specify that?

Thnaks.

**Comment by AndsonYe** [comment]
I have found it....
Thanks anyway.

**Comment by posquit0** [comment]
thank you for your interest on my Awesome-CV!
Good luck!

Sorry for my late reply
