### ISSUE TITLE
First word of cvparagraph in colour rather than first 3 letters

### ISSUE THREAD

**Issue by chappo007** [posquit0/Awesome-CV#104]
Is it possible to change the behaviour of the section for 'cvparagraph' to use the 'awesome' colour for the full length of the first word rather just the first 3 letters.  I can change it for length of characters and probably create individual paragraph sections but would prefer something generic.
Cheers
Mike Chapman

**Comment by ben-e-whitney** [comment]
Do you want the change for all sections or only those containing a `cvparagraph` environment? If it would be acceptable to use the color for the entirety (not just the first word) of all section headings, you could replace the definition of `\@sectioncolor` with
```latex
\def\@sectioncolor#1{%
\ifbool{acvSectionColorHighlight}{\color{awesome}{#1}}{}%
}
````
and the definition of `\sectionstyle` with
```latex
\newcommand*{\sectionstyle}[1]{%
{\fontsize{16pt}{1em}\bodyfont\bfseries\color{text}\@sectioncolor{#1}}%
}
```
If you want just the first word of the section title to be in color, maybe you can use the answers to [this question](http://tex.stackexchange.com/q/316730).

**Comment by chappo007** [comment]
Just the first word.  Thanks for the tip, I'll try it sometime soon.  Cheers.

**Comment by chappo007** [comment]
Just got this working.  It does the job.  I needed to use the latest release.

**Comment by antoine1003** [comment]
Hey,
I try to figure out who can I color the first word in the `cvparagraph` section but I don't see where should I put `\FirstWord` method...
I hope you can help.
Thanks
A.D

**Comment by hsellik** [comment]
It would be nice to have an example of the solution. I couldn't get it working.

**Comment by jocroton** [comment]
@chappo007 would you mind sharing the solution that worked for you? 

Cheers

**Comment by darshak-bhatti** [comment]
What I have done is,
I added 
\newcommand*{\lettersectionstyledark}[1]{{\fontsize{14pt}{1em}\bodyfont\bfseries\color{darktext} #1}}

And modified lettersection to this,

\newcommand{\lettersection}**[2]**{%
  \par\addvspace{2.5ex}
  \phantomsection{}
  \lettersectionstyle{#1}
  **\lettersectionstyledark{#2}**
  \color{gray}\vhrulefill{0.9pt}
  \par\nobreak\addvspace{0.4ex}
}
