### ISSUE TITLE
Out of A4 size when printing out by option "Actual Size"

### ISSUE THREAD

**Issue by lsmgeb89** [posquit0/Awesome-CV#106]
When I print out my cv by option "'Actual Size", it will cut off my name by half.
I know that by most of time, we submit pdf version online.
But we still have some situations to print it out like bringing them to an interview, a job fair, or to be reviewed by some one.

The proof is below image on sample cv.
If I choose "Shrink oversized pages" and print it out, the font is too small to read.
It could be reproduced by sample cv and cover letter.
Thanks!

![out](https://cloud.githubusercontent.com/assets/1487128/22601025/c0cd7658-ea02-11e6-98a1-fa3a98363bd1.png)

**Comment by posquit0** [comment]
There is no print problem for me. Please check again with other computers or printers.

**Comment by johannesbottcher** [comment]
Personally, i would expect that. You are trying to print an A4 document on letter paper. Your print interface even tells you that the document is larger than the paper. And you even have the *Fit* option that will try to make things *fit*.

**Comment by lsmgeb89** [comment]
@johannesbottcher It's a library's printer. I will check it again tomorrow. But I think the default paper size is A4. So I'm trying to print an A4 document on A4 paper.

**Comment by johannesbottcher** [comment]
The print interface at least thinks different.

**Comment by lsmgeb89** [comment]
@posquit0 Sorry, I have double checked it. It's not a bug.
