### ISSUE TITLE
Compile error caused by dropped option of unicode-math package

### ISSUE THREAD

**Issue by lsmgeb89** [posquit0/Awesome-CV#107]
Please check [change history](https://github.com/wspr/unicode-math#change-history) of unicode-math package, the `vargreek-shape=TeX` and `vargreek-shape=unicode` has been dropped.
It will cause compile error if you use latest Tex Live 2016.
Here is the log:

    This is XeTeX, Version 3.14159265-2.6-0.99996 (TeX Live 2016) (preloaded format=xelatex)
     restricted \write18 enabled.
    entering extended mode
    (./cv.tex
    LaTeX2e <2017/01/01> patch level 1
    Babel <3.9r> and hyphenation patterns for 83 language(s) loaded.
    (./awesome-cv.cls
    Document Class: awesome-cv 2016/12/03 v1.6 Awesome Curriculum Vitae Class
    (/usr/local/texlive/2016/texmf-dist/tex/latex/base/article.cls
    Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
    (/usr/local/texlive/2016/texmf-dist/tex/latex/base/size11.clo))
    (/usr/local/texlive/2016/texmf-dist/tex/latex/tools/array.sty)
    (/usr/local/texlive/2016/texmf-dist/tex/latex/enumitem/enumitem.sty)
    (/usr/local/texlive/2016/texmf-dist/tex/latex/ms/ragged2e.sty
    (/usr/local/texlive/2016/texmf-dist/tex/latex/ms/everysel.sty))
    (/usr/local/texlive/2016/texmf-dist/tex/latex/geometry/geometry.sty
    (/usr/local/texlive/2016/texmf-dist/tex/latex/graphics/keyval.sty)
    (/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
    (/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
    (/usr/local/texlive/2016/texmf-dist/tex/generic/ifxetex/ifxetex.sty))
    (/usr/local/texlive/2016/texmf-dist/tex/latex/fancyhdr/fancyhdr.sty)
    (/usr/local/texlive/2016/texmf-dist/tex/latex/xcolor/xcolor.sty
    (/usr/local/texlive/2016/texmf-dist/tex/latex/graphics-cfg/color.cfg)
    (/usr/local/texlive/2016/texmf-dist/tex/latex/graphics-def/xetex.def))
    (/usr/local/texlive/2016/texmf-dist/tex/latex/xifthen/xifthen.sty
    (/usr/local/texlive/2016/texmf-dist/tex/latex/tools/calc.sty)
    (/usr/local/texlive/2016/texmf-dist/tex/latex/base/ifthen.sty)
    (/usr/local/texlive/2016/texmf-dist/tex/latex/ifmtarg/ifmtarg.sty))
    (/usr/local/texlive/2016/texmf-dist/tex/latex/etoolbox/etoolbox.sty)
    (/usr/local/texlive/2016/texmf-dist/tex/latex/setspace/setspace.sty)
    (/usr/local/texlive/2016/texmf-dist/tex/latex/fontspec/fontspec.sty
    (/usr/local/texlive/2016/texmf-dist/tex/latex/l3kernel/expl3.sty
    (/usr/local/texlive/2016/texmf-dist/tex/latex/l3kernel/expl3-code.tex)
    (/usr/local/texlive/2016/texmf-dist/tex/latex/l3kernel/l3xdvipdfmx.def))
    (/usr/local/texlive/2016/texmf-dist/tex/latex/l3packages/xparse/xparse.sty)
    (/usr/local/texlive/2016/texmf-dist/tex/latex/fontspec/fontspec-xetex.sty
    (/usr/local/texlive/2016/texmf-dist/tex/latex/base/fontenc.sty
    (/usr/local/texlive/2016/texmf-dist/tex/latex/base/tuenc.def))
    (/usr/local/texlive/2016/texmf-dist/tex/latex/fontspec/fontspec.cfg)))
    (/usr/local/texlive/2016/texmf-dist/tex/latex/unicode-math/unicode-math.sty
    (/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/ifluatex.sty)
    (/usr/local/texlive/2016/texmf-dist/tex/latex/ucharcat/ucharcat.sty)
    (/usr/local/texlive/2016/texmf-dist/tex/latex/l3packages/l3keys2e/l3keys2e.sty)
     (/usr/local/texlive/2016/texmf-dist/tex/latex/base/fix-cm.sty
    (/usr/local/texlive/2016/texmf-dist/tex/latex/base/ts1enc.def))
    (/usr/local/texlive/2016/texmf-dist/tex/latex/filehook/filehook.sty)

    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !
    ! keyvalue error: "option-unknown"
    ! 
    ! Unknown option 'vargreek-shape' for package unicode-math.
    ! 
    ! See the keyvalue documentation for further information.
    ! 
    ! For immediate help type H <return>.
    !...............................................  
                                                      
    l.385 \ProcessKeysOptions {unicode-math}
                                            
    ?

**Comment by posquit0** [comment]
Thanks to let me know this issue. I'll try to fix this problem ASAP 👍

**Comment by posquit0** [comment]
Solved
