### ISSUE TITLE
Chinese language font support

### ISSUE THREAD

**Issue by vectorliu** [posquit0/Awesome-CV#109]
What is the fastest way to configure the template to support Chinese language? I figured I might have to modify the awesome-cv.cls file. So can it be:

1. Add required fonts to the fonts/ directory;

2. Change the font configuration in the cls file.

However, it is not that elegant since in this way I have to change the cls file again if I want to use the original English language font. So is there a more elegant way? Sorry if the question is naive. I am just new to Latex.

**Comment by johannesbottcher** [comment]
Change the font setting in your main file.
Reading an introduction seems to be a good idea as well.

Am 24.02.2017 06:18 schrieb "vectorliu" <notifications@github.com>:

**Comment by vectorliu** [comment]
@johannesbottcher ,did you mean the following changes made to the main file:

\renewcommand*{\footerfont}{\Kaiti}
\renewcommand*{\bodyfont}{\Kaiti}
\renewcommand*{\bodyfontlight}{\STFangsong}

Just tried and it induced a lot more font-related errors.

**Comment by BrianHuGit** [comment]
I use xeCJK package to build my Chinese cv:

\usepackage{xeCJK}

add this line into the fontawsome.sty file

**Comment by vectorliu** [comment]
Thanks@BrianHuGit. Problem solved.

**Comment by johannesbottcher** [comment]
Guys, you can't just change a file that you don't own. There is a license that needs to be respected.

**Comment by vectorliu** [comment]
Sorry if it breaks some license. We will add this package in the main file, which solves the problem anyway. Thanks for your kindly remind.

**Comment by 77QingLiu** [comment]
@BrianHuGit , where can I find `fontawsome.sty`?

**Comment by Littlesqx** [comment]
> @BrianHuGit , where can I find `fontawsome.sty`?

add into `awesome-cv.cls` can also work

**Comment by linjh1118** [comment]
> @BrianHuGit , where can I find `fontawsome.sty`?

I find  `fontawsome.sty` in https://github.com/plorcupine/latex-fontawesome. Thanks `latex-fontawesome`
