### ISSUE TITLE
How would I go about adding a medium.com font icon?

### ISSUE THREAD

**Issue by nunogoncalves** [posquit0/Awesome-CV#110]
Title says pretty much everything I wanted to ask

**Comment by johannesbottcher** [comment]
Not sure, but his seems to be the same as in https://github.com/posquit0/Awesome-CV/pull/69

**Comment by nunogoncalves** [comment]
I managed to do it. :) I guess I should create a pull request with that.

**Comment by johannesbottcher** [comment]
Little note: You need this symbol/icon, Jimmy needs another one. Carol also needs one. So does Frank. If all do a PR, this template is bloated by a million times within a week. 
What this template needs, is an interface where every user can decide what to put on a CV. 

What is almost as important, no user needs to use a template, as *every* (yes, *EVERY*) template restricts the user. 

Every change to the class file by a user means, the user gets slower (or even no) support.

**Comment by nunogoncalves** [comment]
I totally agree with that. But I just started learning tex, for the single purpose of updating my cv. I'm not yet in he position to help in that. So I'm probably leave that to who knows. :)
