### ISSUE TITLE
Disable double colors only for Sections

### ISSUE THREAD

**Issue by mariob6** [posquit0/Awesome-CV#116]
Hi there,
first of all, I love this theme. I just want to know if it possible to have the sections all in black (no "Edu" in red) while keeping the Locations and Position in red!

Thank you

**Comment by posquit0** [comment]
You can see the comment in your `resume.tex` file :)

```tex
% Set false if you don't want to highlight section with awesome color
\setbool{acvSectionColorHighlight}{true}
```

**Comment by reesemcardle** [comment]
What if I want the whole first word (ex Education) to be red

**Comment by belhssanklouz** [comment]
> What if I want the whole first word (ex Education) to be red

in awesome-cv.cls in line 155
change this code => 
\def\@sectioncolor#1#2#3{%
  \ifbool{acvSectionColorHighlight}{{\color{awesome}#1#2#3}}{#1#2#3}%
}
to this =>
\def\@sectioncolor#1#2#3{%
  \ifbool{acvSectionColorHighlight}{{\color{awesome}#1#2#3}}{\color{awesome}#1#2#3}%
}
