### ISSUE TITLE
How to move header to right?

### ISSUE THREAD

**Issue by ostojicmilica** [posquit0/Awesome-CV#118]
Can you please tell me how to move header on left or right just like you did in version of cover letter with picture?

**Comment by posquit0** [comment]
Please see the comment in the example `.tex` files. :)

```tex
% Print the header with above personal informations
% Give optional argument to change alignment(C: center, L: left, R: right)
\makecvheader[C]
```

**Comment by ostojicmilica** [comment]
Yes, I saw that but this, doesn't work for me, when I add argument header is still in center, and I see [R] argument in the text of header, so can you please reopen this issue?
