### ISSUE TITLE
how to change section colour?

### ISSUE THREAD

**Issue by memoiry** [posquit0/Awesome-CV#129]
Hi

I want to change the color of first three words to sky-blue instead of red, and I have searched for section-colour definition but found nothing related to colour itself. 

What should I do? Thanks!

**Comment by memoiry** [comment]
I have found the answer, thanks!

**Comment by magician03** [comment]
How to resolve this ?

**Comment by me7pako** [comment]
> I have found the answer, thanks!

How did you do?
