### ISSUE TITLE
Spaces at EOL

### ISSUE THREAD

**Issue by johannesbottcher** [posquit0/Awesome-CV#13]
Everywhere, freaking everywhere. 

Please remove them.

http://tex.stackexchange.com/questions/7453/what-is-the-use-of-percent-signs-at-the-end-of-lines  
http://tex.stackexchange.com/q/40946  
http://tex.stackexchange.com/q/19922

**Comment by posquit0** [comment]
Thanks, it was my first LaTeX project, so I didn't catch this issue. Now, I added all of spaces needed.
:+1:
