### ISSUE TITLE
Changing size of photo - keeping original format

### ISSUE THREAD

**Issue by PB-Coaching** [posquit0/Awesome-CV#143]
The shape of the photo is always a square when selecting the option 'rectangle'. My problem is that my photos are rectangles, so parts of the pictures get cut off. This doesn't look good when applying to a job.

I have come so far as to identify the tikz node to be responsible for the picture size and format in the awesome-cv.cls file

```
% Usage: \makecvheader
\newcommand*{\makecvheader}[1][C]{%
  \newcommand*{\drawphoto}{%
    \ifthenelse{\isundefined{\@photo}}{}{%
      \newlength{\photodim}
      \ifthenelse{\equal{\@photoshape}{circle}}%
        {\setlength{\photodim}{1.3cm}}%
        {\setlength{\photodim}{1.9cm}}%
      \ifthenelse{\equal{\@photoedge}{edge}}%
        {\def\@photoborder{darkgray}}%
        {\def\@photoborder{none}}%
      \begin{tikzpicture}%
        \node[\@photoshape, draw=\@photoborder, line width=0.3mm, inner sep=\photodim, fill overzoom image=\@photo] () {};
      \end{tikzpicture}
    }%
```

I tried changes in the \node line, but no success. I want the original format to be kept, when the picture in inserted. Is that possible?

Thanks for your help

**Comment by imageliu** [comment]
I had the same problem, and I googled the  TikZ package.
I still know very little about it, but I found a solution that works for me :
use \path instead of \node:

`      \begin{tikzpicture}%
		\path[fill overzoom image=\@photo] (0,0) rectangle (2.86cm,4cm);
	  \end{tikzpicture}`

You may set the size of your photo by changing (2.86cm,4cm) . 
Have a try~

**Comment by PB-Coaching** [comment]
Thanks, worked for me as well ))

**Comment by theflyingd** [comment]
I would like to add the hairline around the picture, so I used your solution and expanded it with the original code to

\begin{tikzpicture}% 
     \path[\@photoshape, draw=\@photoborder, line width=0.3mm, inner sep=\photodim, fill overzoom image=\@photo] (0,0) rectangle (2.86cm,4cm); 
     \end{tikzpicture}
