### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by eppleshine** [posquit0/Awesome-CV#147]
I have latest MiKTeX and Texmaker 5.0.1 installed in my Windows 10.
I downloaded the Example folder and pasted awesome-cv.cls & fontawesome.sty in this folder. When I opened it, this came. I clicked OK.

![1](https://user-images.githubusercontent.com/26725750/28765699-832fbe40-75e5-11e7-944d-51d1f000db6f.png)

Compiled and it started to download a lot of packages and then it said compile it with XeLaTex or LUALaTex. 
**Compiled with XeLaTex**
![xe](https://user-images.githubusercontent.com/26725750/28765769-dbda1d42-75e5-11e7-91d2-aef59da71703.png)

**Compiled with LUALaTex**
![la](https://user-images.githubusercontent.com/26725750/28765808-110a87ea-75e6-11e7-8336-400fe6a52b11.png)

Please solve these problems. I love this awesome template and want to use it. It's really awesome.

**Comment by hasufell** [comment]
Yeah, this template is missing basic instructions on dependencies and requirements. "It should work with a standard tex distribution" generally is not such an instruction.

**Comment by Deteklover** [comment]
I have exactly same problem !
It would great to have it run on fresh full Miktek install and Tekmaker under Windows 10.

Is there something to check or add in this config to have it run succefully ?

**Comment by jat255** [comment]
@eppleshine Did you install the correct fonts? The error message seems to indicate that FontAwesome, SourceSans Pro, and Roboto are not installed.

**Comment by Deteklover** [comment]
All fonts are in the fonts folder, send with the entire project files

**Comment by justinbass** [comment]
I got this working on Win10 with MiKTeX 2.9 and xelatex (from both Cygwin CLI and TeXStudio) with intense effort of pulling in dependencies manually (downloaded from various sources online) into the main directory where resume.tex lives, as well as removing the symlink for fonts and just moving the whole folder in. There was probably a better way, but this was many years ago. Attaching a snapshot of my directory if it helps. I also made other changes like moving everything into the main resume.tex.
[AwesomeCVDirectories.txt](https://github.com/posquit0/Awesome-CV/files/1345910/AwesomeCVDirectories.txt)

**Comment by divyag6028** [comment]
if you are working on windows, since resume.tex file is inside examples folder, you can place fonts folder too within this folder and execute resume.tex from TeXworks. I too had faced this error, and this is what I have done to make it work.

**Comment by rrryan2016** [comment]
> 
> 
> if you are working on windows, since resume.tex file is inside examples folder, you can place fonts folder too within this folder and execute resume.tex from TeXworks. I too had faced this error, and this is what I have done to make it work. Also in fontawesome.sty, changed line \newfontfamily{\FA}{FontAwesome} to \newfontfamily\fatest{FontAwesome}

IT WORKS. THX

**Comment by OJFord** [comment]
Closed via #344.
