### ISSUE TITLE
Leave first three letters the same

### ISSUE THREAD

**Issue by nonlinearDynamic** [posquit0/Awesome-CV#148]
In the titles of each section, how can I leave the first three letters the same as the rest of the title? I could just make the font the same as the rest of the doc, but I like having the rest of the highlighting although I would like to replace having the locations highlighted with having the dates.

**Comment by nonlinearDynamic** [comment]
Nevermind I figured it out.

**Comment by jat255** [comment]
@nonlinearDynamic Care to share with the class? 😏

**Comment by nonlinearDynamic** [comment]
In the awesome-cv.cls file, line 152 change the boolean from true to false. Fixes the section titles.
