### ISSUE TITLE
Need for appropriate hooks

### ISSUE THREAD

**Issue by johannesbottcher** [posquit0/Awesome-CV#15]
Apparently, users want to customize the template, but like almost any other template ... no hooks

http://tex.stackexchange.com/questions/285848/how-to-add-spaces-between-font-awesome-icons-and-text-in-latex-awesome-resume-c/285900#285900

I will ping Vel

**Comment by johannesbottcher** [comment]
I see you made some changes. Thanks :-)

**Comment by posquit0** [comment]
Oh~ I didn't close this issue cuz I think more places need hooks to easily customize :-)
I'll update ASAP! Thanks to your opinion.

**Comment by johannesbottcher** [comment]
Oh yes, there is potentian for more. But you already included so good hooks, which i found nice :-)

**Comment by posquit0** [comment]
I added \acvSectionTopSkip and \acvEntryTopSkip
