### ISSUE TITLE
How can I make the 'honorlocation' in only one row?

### ISSUE THREAD

**Issue by PFSWcas** [posquit0/Awesome-CV#151]
In the resume, I try to write the 'honorlocation' in one row,  but the result is like this:

![a](https://user-images.githubusercontent.com/15920372/29494135-3d6145fe-85d6-11e7-98f4-5792657700f2.PNG)

Can somebody tell me how to change 'awesome-cv.cls' to put the 'honorlocation' in one row.

**Comment by adityadrs** [comment]
I am facing a similar problem, please do let me know how you handled it.
 Thanks!
