### ISSUE TITLE
Fonts embed issues

### ISSUE THREAD

**Issue by ytian81** [posquit0/Awesome-CV#157]
Hi,

Are the fonts embedded in the PDF? Since these fonts are not commonly used, I would like know whether this fonts are actually embedded in the generated PDF file. If not, how can I embed using Latex command?

Thanks!

**Comment by justinbass** [comment]
$ pdffonts resume.pdf
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
EDRPSQ+Roboto-Bold                   CID TrueType      Identity-H       yes yes yes      5  0
YVIFYE+SourceSansPro-Regular-Identity-H CID Type 0C       Identity-H       yes yes yes      7  0
QSCZRU+Roboto-Italic                 CID TrueType      Identity-H       yes yes yes      9  0
INWXDE+FontAwesome                   CID TrueType      Identity-H       yes yes yes     11  0
BQJRQS+Roboto-Regular                CID TrueType      Identity-H       yes yes yes     13  0
QUCSQV+SourceSansPro-Bold-Identity-H CID Type 0C       Identity-H       yes yes yes     19  0
FWVASC+SourceSansPro-LightIt-Identity-H CID Type 0C       Identity-H       yes yes yes     21  0
QPSNNF+SourceSansPro-Light-Identity-H CID Type 0C       Identity-H       yes yes yes     23  0
PMVHBJ+SourceSansPro-SemiboldIt-Identity-H CID Type 0C       Identity-H       yes yes yes     25  0
UYYCWZ+LMRoman9-Regular-Identity-H   CID Type 0C       Identity-H       yes yes yes     27  0
JQHWXV+LMRoman6-Regular-Identity-H   CID Type 0C       Identity-H       yes yes yes     29  0

This was generated on Windows 10 using MiKTeX 2.9 (xelatex). Generally I've seen my resume look good on Mac, Windows, and Linux on various versions. I'm assuming font embedding is a default option for xelatex.
