### ISSUE TITLE
cannot find FontAwesome (I am using MacTex)

### ISSUE THREAD

**Issue by alexanderhanboli** [posquit0/Awesome-CV#166]
`the font "FontAwesome" cannot be found`

I am using MacTex which should already contain everything I need (including TexLive)

**Comment by peterklijn** [comment]
a

**Comment by mmuratarat** [comment]
Check this pull request: https://github.com/posquit0/Awesome-CV/pull/98

**Comment by OJFord** [comment]
Closed via #344.
