### ISSUE TITLE
line cuts

### ISSUE THREAD

**Issue by prempalsingh** [posquit0/Awesome-CV#17]
I was just trying out your template on sharelatex and facing this issue - 
![screenshot from 2016-01-11 03-49-23](https://cloud.githubusercontent.com/assets/9432975/12224479/a0af4a72-b817-11e5-8e82-4f4f5e07b7f1.png)

**Comment by posquit0** [comment]
Hi, it's same issue with this(https://github.com/posquit0/Awesome-CV/pull/11). And it's already fixed. However, it'll take some times for ShareLaTeX and OverLeaf to be up-to-date.

Try to use latest source code from here.

Thanks!
