### ISSUE TITLE
Package pgfkeys Error

### ISSUE THREAD

**Issue by MichaelLiang12** [posquit0/Awesome-CV#178]
When I ran demo `coverletter.tex`, it went wrong and outputed 
`
! Package pgfkeys Error: I do not know the key '/tikz/fill overzoom image' and 
I am going to ignore it. Perhaps you misspelled it.
`

I guess there is something wrong with the line
`
\photo[circle,noedge,left]{./examples/profile}
`

How to fix it?

**Comment by mahbubcseju** [comment]
How to solve this problem ? I a facing the similiar problem

**Comment by MichaelLiang12** [comment]
The Tex version is too old, update it to V2016. [More details](https://github.com/posquit0/Awesome-CV/issues/190)
