### ISSUE TITLE
Skills section

### ISSUE THREAD

**Issue by Kanwar245** [posquit0/Awesome-CV#18]
I think addition of a Technical Skills section will make the resume complete. Do you think this is possible?

**Comment by posquit0** [comment]
It already has skills sections :)

[TeX file](https://github.com/posquit0/Awesome-CV/blob/master/examples/cv/skills.tex)
[PDF](https://github.com/posquit0/Awesome-CV/blob/master/examples/cv.pdf)

**Comment by Kanwar245** [comment]
Oh! I didn't notice that, thank you!

On Mon, Jan 18, 2016 at 11:03 PM, Byungjin Park <notifications@github.com>
wrote:

> It already has skills sections :)
>
> TeX file
> <https://github.com/posquit0/Awesome-CV/blob/master/examples/cv/skills.tex>
> PDF <https://github.com/posquit0/Awesome-CV/blob/master/examples/cv.pdf>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/posquit0/Awesome-CV/issues/18#issuecomment-172731528>.
>



-- 
Regards,
Kanwar Gill
