### ISSUE TITLE
! fontspec error: "font-not-found"

### ISSUE THREAD

**Issue by ooker777** [posquit0/Awesome-CV#181]
All the seemingly used fonts are not found, though I've installed them. One example error is:

```
! fontspec error: "font-not-found"
! 
! The font "Roboto-Thin" cannot be found.
! 
! See the fontspec documentation for further information.
! 
! For immediate help type H <return>.
```

I use Windows 10, MiKTeX.

**Comment by ivasim** [comment]
Just using \usepackage{fontspec} is not going to be enough in case you want to use custom fonts.
If you use the example Latex templates provided within this project you don't have to use fontspec.

**Comment by bkolada** [comment]
I had the same problem with font awesome and installing font in the system was enough.

**Comment by cbarrick** [comment]
Installing the font system wide is a hack. I think I've fixed it though. You just have to delete line 12 from `fontawesome.sty`. I.e. delete this:

```
% Define shortcut to load the Font Awesome font.
\newfontfamily{\FA}{FontAwesome}
```

This works because the font family is defined _properly_ in `awesome-cv.cls` already.

**Comment by johannesbottcher** [comment]
You cannot just change a copyrighted file.
Also, installing a font system wide is not a hack.

Am 06.02.2018 03:25 schrieb "Chris Barrick" <notifications@github.com>:

**Comment by niranjantdesai** [comment]
Check the font directory in the source files. If the style files are in the "examples" folder, fontdir should be ../fonts/ in the main .tex file as well as ``awesome-cv.cls``.

**Comment by 77QingLiu** [comment]
same issue

**Comment by 77QingLiu** [comment]
@cbarrick , Still get the error after remove line 12 in my case.

**Comment by 77QingLiu** [comment]
My issue has been removed by moving the `fonts folder` under `the examples folder`. I think this should solve your problem too.

**Comment by inmybrain** [comment]
I had the same problem, and [this](https://github.com/posquit0/Awesome-CV/issues/181#issuecomment-363289393) worked for me.

**Comment by Berkmann18** [comment]
> Installing the font system wide is a hack. I think I've fixed it though. You just have to delete line 12 from `fontawesome.sty`. I.e. delete this:
> 
> ```
> % Define shortcut to load the Font Awesome font.
> \newfontfamily{\FA}{FontAwesome}
> ```
> 
> This works because the font family is defined _properly_ in `awesome-cv.cls` already.

That alongside commenting out l.14-16, helped getting the FA icons to show up.
> \newcommand*{\faicon}[1]{{
>   \FA\csname faicon@#1\endcsname
> }}

**Comment by abuck2** [comment]
@johannesbottcher Isn't it licensed under CC-BY-SA? I don't see the problem in modifying the file, or am I missing something?

**Comment by Daisy1111** [comment]
> My issue has been removed by moving the `fonts folder` under `the examples folder`. I think this should solve your problem too.

This way works for me too!! Amazing!
