### ISSUE TITLE
Awesome-CV, do you not support Chinese?

### ISSUE THREAD

**Issue by lovebaicai** [posquit0/Awesome-CV#184]
Hi，
    I use Awesome-CV, but the Chinese can not be displayed, is it because of the format of the characters? How to modify, can support Chinese?
   Please help me.Tks!

**Comment by BrianHuGit** [comment]
https://github.com/posquit0/Awesome-CV/issues/109

**Comment by lovebaicai** [comment]
@BrianHuGit  Thank you very much!
slove it !

**Comment by ravijo** [comment]
@lovebaicai 

Hi there,

if you’re still looking for a working template, you can find it at [ravijo/Awesome-CV](https://github.com/ravijo/Awesome-CV). Note that it uses `\usepackage{xeCJK}`, and sample TeX files in Japanese are provided; these can be easily adapted for Chinese as needed. Feel free to use it. 

Thank you.
