### ISSUE TITLE
How can I add small icon logos next to experience entries?

### ISSUE THREAD

**Issue by parktimothy** [posquit0/Awesome-CV#187]
![logoentries](https://user-images.githubusercontent.com/28663630/35081024-5b276472-fbc6-11e7-8aa4-ded9aebd3376.png)
I want to make it something like this and was wondering if that was possible with Awesome-Cv

**Comment by StephYao** [comment]
Hello,  did you figure it out?

**Comment by parktimothy** [comment]
Nope, I'm not sure if this is possible
