### ISSUE TITLE
Legal issue (giving appropriate credit)

### ISSUE THREAD

**Issue by hkoel01** [posquit0/Awesome-CV#20]
In https://creativecommons.org/licenses/by-sa/4.0/ it states that:

**Attribution** _— You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use._

This is slightly complicated, since you can interpret this as a need to give credit on the CV and/or cover letter that someone wants to hand in to a company. If misunderstood, this might end up giving the applicant some trouble?
If you want to have credit given on the CV or CL, why not include a short credit on the bottom right, where there is still free space?

**Comment by johannesbottcher** [comment]
This is the problem with software licenses. *I am not a lawyer*, so you cannot rely on my words. 
What is licensed is the tex file, you shall keep the license statement and mark anything that you changed. Which is a bit ridicoulous for a tex file (as opposed to a class file). It is complicated to define what a template even is. 

Nevermind, your pdf-output is yours.
Think about the tex as a baking recipe. You can copy a recipe from a book into your personal notebook, you add a note where you found it an what you changed. But you don't say to people: Look, this is made using book XYZ (unless peoplle ask `;-)`).

**Comment by hkoel01** [comment]
Thanks for the input.
But the same would apply to open source code, where the compiled product (program) is still supposed to give credit the people behind the source code. The product of a compilation process is not always yours in its entirety.
And since CV and motivational letters, which are used to get a job (where you might end up being in a higher position at a later stage in live), aren't trivial documents, I just wanted to bring up the point... 
I am no lawyer as well, but this kind of keeps me from using it myself, even though I like the template.

**Comment by johannesbottcher** [comment]
Well, we have to wait for @posquit0 to say something. 

Related http://tex.stackexchange.com/questions/82713/is-a-pdf-output-from-a-latex-document-a-derived-work-from-the-lppl-standard-p

The one you linked to also has an answer from  me.

**Comment by posquit0** [comment]
Well, I want to listen more opinions from others. //I am not a lawyer//
I don't fully understand about the license of CC-BY-SA 4.0, however it's not my intention. I don't want to put the license of Awesome CV on the bottom of output document.

I have a mind to change the license of the template files if it's needed. Please comment more opinions about this issue.

**Never mind, your PDF is yours. You don't need to put the license on your document**

**Comment by justinbass** [comment]
Legally, a license as only good as it can be defended. Author has no intention to copyright the pdf files, and having been to many career fairs, I can attest that this template is ubiquitous and has never caused any issues. This is a non-issue.

**Comment by cxkoda** [comment]
To express the copyright intent of @posquit0 I would suggest adding a license file to the repo.
Maybe the one as proposed in #245 ?
