### ISSUE TITLE
Go to Font Awesome 5

### ISSUE THREAD

**Issue by rememberYou** [posquit0/Awesome-CV#206]
The version 5 of Font Awesome is [available](https://www.ctan.org/pkg/fontawesome5) in LaTeX, it allows you to use the new Font Awesome icons including the Pro icons. It would be ideal to replace the previous `fontawesome` package with `fontawesome5` in the `awesome-cv.cls` file and adapt the icons used for existing commands.

If this change is accepted, I can make a pull request with this change.

**Comment by juandpinto** [comment]
Any update on this? I'd love to be able to use the Mastodon icon found in Font Awesome 5.

**Comment by ashwinvis** [comment]
See #235
