### ISSUE TITLE
Awesome-CV and Windows 8

### ISSUE THREAD

**Issue by Riin** [posquit0/Awesome-CV#21]
Hi there,

i have a problem creating a pdf from cv.tex. I get this error
LaTeX Error: Missing \begin{document}
! Undefined control sequence. \fontdir
! Undefined control sequence. \colorlet
[...]

I use following tools: Texlive 2014 and Xelatex in TexMaker with Windows 8.
I tried with command line "path\to\xelatex.exe cv.tex" but i get an error:
Undefined control sequence. \documentclass[11pt, a4paper]{awesome-cv}  
[...]

Any help is appreciated.

**Comment by johannesbottcher** [comment]
I think this is not an issue of the template buth with compiling a tex document in general. You should ask on latex-community.org or tex.stackexchange com
Give as much information as possible.

**Comment by posquit0** [comment]
I agree with @johannesbottcher 

Btw, do you have a class file(awesome-cv.cls) on same directory with cv.tex?

**Comment by posquit0** [comment]
I decided to close this issue. Please send me an email If you need more help! Thanks :+1:

**Comment by altaha** [comment]
I had the same issue with Windows 10, and I tried both MikTex and Tex Live... After much hair pulling, the issue was fixed by replacing the files awesome-cv.cls and fontawesome.sty in the examples directory with the same named files in the parent directory. I guess the current files are supposed to act as includes to the ones in the parent directory?

**Comment by posquit0** [comment]
Ummm, I think it's because files in examples  are unix link file. These
files are just linking original files in the parent directory.

Thanks to your solution!

2016년 4월 11일 (월) 오전 11:33, Ahmed <notifications@github.com>님이 작성:

**Comment by ooker777** [comment]
I propose this to be added in the front page. Something like:

>#Windows users
Replacing the files `awesome-cv.cls` and `fontawesome.sty` in the examples directory with the same named files in the parent directory

**Comment by mmacheerpuppy** [comment]
@posquit0  Just ran into this issue and after some messing on managed to get it to work by replacing the files as stated. I think for newer Latex users on Windows machines who are experiencing this issue there should be a statement about this on the README.md [it would be helpful].

**Comment by juan-aquino** [comment]
@posquit0 

Like the user above said, you *really* should add a sentence in the README saying this:
> ### Windows users
> Replace the files `awesome-cv.cls` and `fontawesome.sty` in the examples directory with the same named files in the parent directory if you are having compilation issues.

I spent hours trying to work it out myself. Please, save people some time.

**Comment by oleksis** [comment]
Before clone the repository you can set the config:

```bash
git config --global core.symlinks true
```
