### ISSUE TITLE
Support Multiple GitHub Repositories in Resume Header

### ISSUE THREAD

**Issue by carlcorder** [posquit0/Awesome-CV#212]
Hello,

First, let me say that I am really enjoying Awesome CV, the style and layout are fantastic! I would like to know if there is a way to display several (say 3) GitHub repositories at the top?

I have taken a look into awesome-cv.cls and noticed:

% Defines writer's github (optional)
% Usage: \github{<github-nick>}
\newcommand*{\github}[1]{\def\@github{#1}}

Would there be a way to simply modify this to achieve the desired effect?

**Comment by thedch** [comment]
Hi Carl —

A hacky way to do this would be to define as many github commands as you want, `github1`, `github2`, etc, and then your `resume.tex` file would look like:

```
...
\github{thedch}
\github1{other_github}
\github2{other_other_github}
...
```

Then, in `awesome-cv.cls`, find this bit of code:

```
      \ifthenelse{\isundefined{\@github}}
        {}
        {
          \ifbool{isstart}
            {
              \setbool{istart}{false} 
            }
            {\@headersocialsep}
          \href{https://github.com/\@github}{github.com/\@github }
        }
```
and duplicate it, changing the `\ifthenelse{\isundefined{\@github}}` to `\ifthenelse{\isundefined{\@github1}}`, etc. 

I'm not positive this will work, but try it! 😄

**Comment by carlcorder** [comment]
@thedch worked like a charm. Thanks for your response!
