### ISSUE TITLE
Numbers in cventryEducation unusually small compared to text

### ISSUE THREAD

**Issue by na21** [posquit0/Awesome-CV#215]
Trying to add GPA next to the name of the degree and the GPA itself is very small compared to the text. I've tried using \normal or \large but the font looks different than the default font. Example:

{Bachelor of Science (B.S) in Computer Science, GPA: 3.5}

**Comment by magician03** [comment]
Why is this closed ? Did you resolve the issue ? Please post the resolution here if you've resolved it.

**Comment by magician03** [comment]
One solution is to enclose it in $$ or inside /textit{}
