### ISSUE TITLE
How to add subitems 

### ISSUE THREAD

**Issue by Unous1996** [posquit0/Awesome-CV#219]
How to add subitems to each items in each experience, like:

experience1
- item1
   subitem1
   subitem2
- item2
   subitem1
   subitem2
- item3
   subitem1
   subitem2

**Comment by Nippius** [comment]
I just had this issue today and it's actually quite easy. You just need to use the command 
```\begin{itemize}``` on the same level as ```\item```.

For example, this code:
`\begin{cvitems}
        \item {A}
         \begin{itemize}
            \item {B}
            \item {C}
        \end{itemize}
        \item {D}
    \end{cvitems}`

Will give the following output:

![image](https://user-images.githubusercontent.com/1528640/47532856-6af03580-d8a9-11e8-8103-5ac06b1a4193.png)


Note: I only tested this for `\cventry`

**Comment by OJFord** [comment]
Thanks for answering that Nippius (I won't ping after so long!) - closing as I assume not least from the thumbs up that this is fine.
