### ISSUE TITLE
How to add skills section?

### ISSUE THREAD

**Issue by riyashah17** [posquit0/Awesome-CV#224]
Cannot find any skills section in resume when edited on sharelatex. However, it can be found in examples of this repository. How to add it?

**Comment by pawanmishra** [comment]
@riyashah17 You can define skill section using cventry. e.g.

`
%-------------------------------------------------------------------------------
%	CONTENT
%-------------------------------------------------------------------------------
\begin{cvskills}

%---------------------------------------------------------
  \cvskill
    {Languages} % Category
    {Scala, Java, C\#, Python} % Skills

\end{cvskills}
`

Have this in a file & then include the file in the main resume.tex.
