### ISSUE TITLE
Error: Command \FA already defined

### ISSUE THREAD

**Issue by OJFord** [posquit0/Awesome-CV#234]
https://github.com/posquit0/Awesome-CV/blob/master/awesome-cv.cls#L164 causes:
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! LaTeX error: "xparse/command-already-defined"
!
! Command '\FA' already defined!
!
! See the LaTeX3 documentation for further information.
!
! For immediate help type H <return>.
!...............................................
```

due to a change in `fontspec` as described in: https://tex.stackexchange.com/a/453198/73121.

**Comment by jeongwhanchoi** [comment]
You should specify the extension of the font(e.g. otf).
This is my pull request with adding the extension `.otf`.
[Pull Request](https://github.com/posquit0/Awesome-CV/pull/236)

**Comment by Thaodan** [comment]
I used setfont instead of newfont and now it runs again. Adding the extensions to the font didn't help.

**Comment by haseebmahmud** [comment]
> I used setfont instead of newfont and now it runs again. Adding the extensions to the font didn't help.

Could you tell me what you did exactly? In a bit detail?

**Comment by redragonx** [comment]
Arch Linux users: You'll need https://aur.archlinux.org/packages/ttf-font-awesome-4/ (Version 4 in AUR) then edit awesome-cv.cls file at line 164: to have 
```
\setfontfamily\FA[Path=\@fontdir]{FontAwesome}
% Set font for header (default is Roboto)
\setfontfamily\headerfont[
  Path=\@fontdir,
  UprightFont=*-Regular,
  ItalicFont=*-Italic,
  BoldFont=*-Bold,
  BoldItalicFont=*-BoldItalic,
]{Roboto}

\setfontfamily\headerfontlight[
  Path=\@fontdir,
  UprightFont=*-Thin,
  ItalicFont=*-ThinItalic,
  BoldFont=*-Medium,
  BoldItalicFont=*-MediumItalic,
]{Roboto}

```

**Comment by ashwinvis** [comment]
@redragonx I am on ArchLinux, but I didn't need FontAwesome 4
```console
$ pacsearch ttf-font
...
community/ttf-font-awesome 5.5.0-1 [installed]
    Iconic font designed for Bootstrap
```

Just the patching the .cls file was sufficient
```diff
diff --git a/awesome-cv.cls b/awesome-cv.cls
index d1c1074..48c3da2 100644
--- a/awesome-cv.cls
+++ b/awesome-cv.cls
@@ -161,7 +161,7 @@
 %                Configuration for fonts
 %-------------------------------------------------------------------------------
 % Set the FontAwesome font to be up-to-date.
-\newfontfamily\FA[Path=\@fontdir]{FontAwesome}
+\setfontfamily\FA[Path=\@fontdir]{FontAwesome}
 % Set font for header (default is Roboto)
 \newfontfamily\headerfont[
   Path=\@fontdir,
```

**Comment by chang48** [comment]
> Just the patching the .cls file was sufficient
> 
> ```diff
> diff --git a/awesome-cv.cls b/awesome-cv.cls
> index d1c1074..48c3da2 100644
> --- a/awesome-cv.cls
> +++ b/awesome-cv.cls
> @@ -161,7 +161,7 @@
>  %                Configuration for fonts
>  %-------------------------------------------------------------------------------
>  % Set the FontAwesome font to be up-to-date.
> -\newfontfamily\FA[Path=\@fontdir]{FontAwesome}
> +\setfontfamily\FA[Path=\@fontdir]{FontAwesome}
>  % Set font for header (default is Roboto)
>  \newfontfamily\headerfont[
>    Path=\@fontdir,
> ```

I have the same error. But thanks to @ashwinvis, the patch fixes the problem.
