### ISSUE TITLE
Full Color Section Heading (Solved)

### ISSUE THREAD

**Issue by dcsim** [posquit0/Awesome-CV#25]
**UPDATE:** Making this change in awesome-cv.cls to line 215, and making the second change on line 153 solved it.   
`\newcommand*{\sectionstyle}[1]{{\fontsize{16pt}{1em}\bodyfont\bfseries%
      \color{**awesome-skyblue**}\@sectioncolor #1}}`

`% Awesome section color
\def\@sectioncolor**{}**{%
  \ifbool{acvSectionColorHighlight}{{\color{awesome}**{}}}{}**%
}` 

![Modified Output](http://i.imgur.com/nM82uhc.png)

**Comment by posquit0** [comment]
Hmmm... I don't know what do you ask exactly, sorry. If you want to disable section color highlighting, on your `resume.tex`, just set this `\setbool{acvSectionColorHighlight}{false}`

If it is not the answer you want, please write in more detail.

**Comment by MrCleanWithHair** [comment]
Rather than have only three letters be awesome colors, I'd like to have the entire section heading awesome color. Below is what I believe to be the relevant code.

% Awesome section color
\def\@sectioncolor{}{%
  \ifbool{acvSectionColorHighlight}{{\color{awesome}{}}}{}%
}

**Comment by posquit0** [comment]
You can change the color on `\sectionstyle` in 224 line number.

**Comment by s37syed** [comment]
Can you re-open this ticket? I want to know how to enable color for entire section (not just first three characters of Section Header Name)

Thanks!

**Comment by dcsim** [comment]
The original post on this issue was updated with how I managed to get it done to be more than the first 3 letters of a section heading, and an image of what it looks like.

**Comment by t3chguy** [comment]
Would love to see this being configurable, as in 0-n number of characters to be coloured, with the option to colour all characters.

**Comment by s37syed** [comment]
Hi @dcsim,

Your fix does not work because you use an old version of LaTeX. I figured it out though.

The line to change as of November 16th, 2016 to get this working is to modify awesome-cv.cls, Line 155 and 156 for the following:

% Awesome section color
\def\@sectioncolor{\color{awesome}}

This will make the section colour entirely "awesome" (the variable, and quite literally), based on your setting in resume.tex

Thanks,

Shah

**Comment by yashladd** [comment]
How to change the heading to a custom color ?

**Comment by sadransh** [comment]
@yashladd there is a line to change in main tex file similar to this : 
 \definecolor{awesome}{HTML}{CA63A8}
