### ISSUE TITLE
How to change picture dimensions?

### ISSUE THREAD

**Issue by v-simon** [posquit0/Awesome-CV#252]
I'd like to use a picture in wide format instead of the circle/square shape. 

I've identified the code that generates the image but I don't know how to specify @photodim as a twodimensional rectangular shape.

```
\newcommand*{\makecvheader}[1][C]{%
  \newcommand*{\drawphoto}{%
    \ifthenelse{\isundefined{\@photo}}{}{%
      \newlength{\photodim}
      \ifthenelse{\equal{\@photoshape}{circle}}%
        {\setlength{\photodim}{1.3cm}}%
        {\setlength{\photodim}{1.8cm}}%
      \ifthenelse{\equal{\@photoedge}{edge}}%
        {\def\@photoborder{darkgray}}%
        {\def\@photoborder{none}}%
      \begin{tikzpicture}%
        \node[\@photoshape, draw=\@photoborder, line width=0.3mm, inner sep=\photodim, fill overzoom image=\@photo] () {};
% , fill overzoom image=\@photo
      \end{tikzpicture}
    }%
```

 Basically what I want, would be this `\setlength{\photodim}{{1.8cm}{2.7cm}}`
This does not work as \setlength only works in one dimension. 
Does anyone know how to do this?

Thanks in advance.

**Comment by v-simon** [comment]
I found a workaround for this. In addition to 'inner sep', \node also accepts 'inner xsep' and 'inner ysep'. For some reason I couldn't find the documentation for this anywhere.
So i did this:
`\node[\@photoshape, draw=\@photoborder, line width=0.3mm, inner xsep=1.8cm, inner ysep=2.7cm, fill overzoom image=\@photo] () {};`

A better fix would probably be to separate photodim into multiple parameters, i.e. xdim, ydim and photodim. This would map the functionality into the \photo function.

**Comment by shirzartenwer** [comment]
Why don't you directly change here:

`        {\setlength{\photodim}{1.3cm}}%
        {\setlength{\photodim}{1.8cm}}%`

I couldn't see the difference of defining the width and height separately in 2 lines or together, can you illustrate if there is a difference?

**Comment by v-simon** [comment]
> Why don't you directly change here:
> 
> ` {\setlength{\photodim}{1.3cm}}% {\setlength{\photodim}{1.8cm}}%`
> 
> I couldn't see the difference of defining the width and height separately in 2 lines or together, can you illustrate if there is a difference?

I'm assuming this is the code you're referring to

`\ifthenelse{\equal{\@photoshape}{circle}}%
        {\setlength{\photodim}{1.3cm}}%
        {\setlength{\photodim}{1.8cm}}%`

The two bottom lines do not set the width and height of the picture. They are part of of the ifthenelse clause in the first line which depends on the photoshape.

I've looked into this again and split up the dimensions into 2 lengths as suggested in my previous post.

`\newcommand*{\makecvheader}[1][C]{%
  \newcommand*{\drawphoto}{%
    \ifthenelse{\isundefined{\@photo}}{}{%
      \newlength{\photoydim}%
      \newlength{\photoxdim}%
      \ifthenelse{\equal{\@photoshape}{circle}}%
        {\setlength{\photoydim}{1.3cm}\setlength{\photoxdim}{\photoydim}}% circle
        {\setlength{\photoydim}{1.8cm}\setlength{\photoxdim}{2.7cm}}% rectangle
      \ifthenelse{\equal{\@photoedge}{edge}}%
        {\def\@photoborder{darkgray}}%
        {\def\@photoborder{none}}%
      \begin{tikzpicture}%
        \node[\@photoshape, draw=\@photoborder, line width=0.3mm, inner ysep=\photoydim, inner xsep=\photoxdim, fill overzoom image=\@photo] () {};
      \end{tikzpicture}
    }%
`
I think this is good enough for what I was trying to do. Obviously it would be useful to just read the correct dimensions from the image but I don't know how to do that.
