### ISSUE TITLE
Show hyperlinks

### ISSUE THREAD

**Issue by nikitavoloboev** [posquit0/Awesome-CV#253]
Currently hyperlinks are not indicated in any way. It would be nice to showcase what text is actually a hyperlink in descriptions, currently there is no way to see this.

**Comment by sonali9696** [comment]
I have the same issue. Could you please help by letting us know how we can indicate the presence of a hyperlink?

**Comment by Berkmann18** [comment]
Have you tried using `\url{https://url.here}` and `\href{https://url.here}{text}`?

**Comment by nikitavoloboev** [comment]
I tried to use \href that works but it doesn't underline links or anything.

\url one doesn't work for me.

**Comment by nikitavoloboev** [comment]
@sonali9696 https://github.com/nikitavoloboev/cv/blob/master/cv/projects.tex#L8

Has a hyperlink. So I guess you can detect it by users using `\href`?

**Comment by dbstern** [comment]
Underlining is a good way to indicate hyperlinks but I think they don't fit that well with the rest of the "visual" of this document. I used icons from font-awesome beside hyperlinks (like the ones in header).

**Comment by DanielSaromo** [comment]
Hello. I managed to add a small box around each hyperlink text. Add this in the preamble: 

```
\usepackage[]{hyperref}
\hypersetup{
            urlbordercolor={0 0 1},
            pdfborder = {1 1 1}
}
```

To add a hyperlink, use: `\href{your.url.com}{your text}`. The default border color for URLs is cyan. Code adapted from [here](https://tex.stackexchange.com/questions/67446/change-colour-of-boxes-surrounding-links-in-hyperref) and [here](https://tex.stackexchange.com/questions/210640/no-border-around-hyperlinks-with-hyperref). I am compiling Awesome-CV with XeLaTeX in Overleaf.
