### ISSUE TITLE
How to input unicode characters?

### ISSUE THREAD

**Issue by TongRuizheWithGzz** [posquit0/Awesome-CV#260]
I want to add some Chinese characters(such as my name in the header of the resume) but the output file simply omits these characters. Then I thought I should specify Chinese fonts to make it work. So I add 
```
\documentclass[11pt, a4paper]{awesome-cv}
\usepackage{fontspec}   % specify the fonts
\setmainfont{STSongti-SC-Regular}
```
But it still failed. What should I do? Thanks a lot~

**Comment by andiac** [comment]
#109
