### ISSUE TITLE
No cvitems

### ISSUE THREAD

**Issue by chashmeetsingh** [posquit0/Awesome-CV#264]
Where there are no cvitems and that part is left blank (in case of education when there are no bullet points), it leaves a lot of space between two items. I wanted to know how to decrease that space.

**Comment by pawanmishra** [comment]
@chashmeetsingh were you able to figure out on how to get rid of extra space? If yes, then can you please share the solution here? Thanks.

**Comment by chashmeetsingh** [comment]
No, I wasn't able to do I used sketch for designing this.
