### ISSUE TITLE
Unable to format publications in the latest build

### ISSUE THREAD

**Issue by ravijo** [posquit0/Awesome-CV#284]
I am not able to format the publication section in the latest build. However, it works fine with an old build available [here](https://github.com/posquit0/Awesome-CV/tree/34e2be930b1800266d0aed054c01fc9ad553a402)

Let me explain it in detail. I have a `.bib` file which contains all of my publications. I want to add them inside the CV like following.
```
\input{cv/publications.tex}
```

There are many similar questions/pull requests here, such as [Issue 271](https://github.com/posquit0/Awesome-CV/issues/271), [Req. 21](https://github.com/posquit0/Awesome-CV/pull/23), [Req. 279](https://github.com/posquit0/Awesome-CV/pull/279), [Issue 81](https://github.com/posquit0/Awesome-CV/issues/81), [Issue 38](https://github.com/posquit0/Awesome-CV/issues/38), [Req. 23](https://github.com/posquit0/Awesome-CV/pull/23)  but don't contain an answer.

_Can someone please provide a working example with the latest code?_

**Comment by ravijo** [comment]
Any suggestions, please?

**Comment by aminmkhan** [comment]
@ravijo Have you tried using the following version?

https://github.com/aminmkhan/Awesome-CV/tree/feature/publications-biblatex

**Comment by ravijo** [comment]
@aminmkhan: Thank you very much for the suggestion. Lately, I forked this repository and implemented my version. You can check it out [here](https://github.com/ravijo/Awesome-CV).  

This is how my version looks [like](https://github.com/ravijo/Awesome-CV/blob/master/examples/cv.pdf).

Thank you.

**Comment by aminmkhan** [comment]
Thanks @ravijo. If you get a chance, can you please submit a PR at [aminmkhan/Awesome-CV](https://github.com/aminmkhan/Awesome-CV ), and I will try to integrate your modifications.

**Comment by ravijo** [comment]
@aminmkhan: done. have a look [here](https://github.com/aminmkhan/Awesome-CV/pull/7)
