### ISSUE TITLE
How to make honors section span multiple pages instead of jumping to next page?

### ISSUE THREAD

**Issue by elsavi** [posquit0/Awesome-CV#288]

**Comment by arosen93** [comment]
This is an issue with how `cvhonors` is defined. It uses `tabular*`, which can't span multiple pages. I think it would require a rewrite to use `longtable`, as mentioned on #341. I haven't found a good solution yet though.

**Comment by OJFord** [comment]
Thanks for the report, just closing in favour (despite it being newer) of #331.
