### ISSUE TITLE
Sample Resumes

### ISSUE THREAD

**Issue by sandeepnegi1996** [posquit0/Awesome-CV#294]
Thank you for creating this repository this is very helpful

Can we create one folder inside which everyone can upload their resume we can put all the resume inside a folder. So that if a person is in different professions can use the sample resume. Right now the resume is mostly focused on the technical person but in that case, it can provide value to a larger set of people.

**Comment by OJFord** [comment]
No, I think that's out of scope. The goal here is a template for a nice CV _format_, not a template and education/advice for exactly what to include for different industries/roles etc.
