### ISSUE TITLE
Multiple title in one company

### ISSUE THREAD

**Issue by Naich** [posquit0/Awesome-CV#3]
Hi 

I am trying to add multiple titles to one firm.

Is there a built-in way to achieve this?

like:

Company A
Sales Manager (2009-PRESENT)
Sales (2005-2009)
experience 1
experience 2
experience 3

or

Company B
Fund Manager(2015-PRESENT)
point a
Trader(2013-PRESENT)
point b
point c

**Comment by posquit0** [comment]
Hi,
You can try this

1. Pull latest source code from here
2. Write 2 cv entry like below:
\cventry
    {First Position}
    {The Company}
    {Seoul, S.Korea}
    {Aug. 2014 - Exp. Apr. 2016}
    {
      \begin{cvitems}
        \item {Implemented blahahaha}
        \item {Improved blahaha}
      \end{cvitems}
    }
  \cventry
    {Second Position}
    {}
    {}
    {Jan. 2013 - Feb. 2013}
    {
      \begin{cvitems}
        \item {Developed blahaha}
      \end{cvitems}
    }
