### ISSUE TITLE
Top Align

### ISSUE THREAD

**Issue by damiankward** [posquit0/Awesome-CV#308]
Using the {cvskill} tag to list Demonstrated Skills, but I'm having difficulty getting the bold text to align to the top of the paragraph. I've tried '[t]' flags in the \begin{tabular*] line, but have not had any success.

Image for clarity:  https://i.imgur.com/WSkevGt.png

**Comment by debsuvra** [comment]
Check https://github.com/posquit0/Awesome-CV/pull/182

**Comment by asan-emirsaleh** [comment]
I have the same issue too

**Comment by OJFord** [comment]
Closing as a duplicate of #136
