### ISSUE TITLE
Projects Section?

### ISSUE THREAD

**Issue by mtantawy** [posquit0/Awesome-CV#31]
I was wondering if there is a section for projects?
If not, besides recommending it, can you give me a quick guide on how to create one or at least how to clone an existing section and start tweaking it?

**Comment by johannesbottcher** [comment]
```syntax=latex

\cvsection{Projects}
\begin{cvitems}
\item Project Gorilla
\item Project Wombat
\end{cvitems}
```

**Comment by mtantawy** [comment]
Thanks for the help.
