### ISSUE TITLE
Not able to change font size and font family

### ISSUE THREAD

**Issue by RadheTians** [posquit0/Awesome-CV#311]
I'm trying to change font size and font family but I'm not able to change this.

**Comment by sinia** [comment]
Can confirm this issue. For example changing 11pt to 20pt in the code below does not result in larger font size. 
`
\documentclass[11pt, a4paper]{awesome-cv}
`

**Comment by RadheTians** [comment]
Hi, @sinia thank you for your response and sorry for the late reply, Yes I tried by your idea but it didn't work.

**Comment by tszabo-ro** [comment]
The reason why what @sinia mentioned won't work is that all the font sizes are defined in the .cls file for all parts of the text. You can change the font size for the specific regions of your document in the class file.
Under the "Configuration for styles" heading you will find a bunch of definitions like:
`\newcommand*{\letteropeningstyle}[1]{{\fontsize{10pt}{1em}\bodyfontlight\bfseries\color{black} #1}}
`
You'll have to edit the font size in these blocks.

**Comment by OJFord** [comment]
A PR to make these configurable would be good, but otherwise closing as an answered question.
