### ISSUE TITLE
Boolean '\ifistart' undefined.

### ISSUE THREAD

**Issue by nipunbatra** [posquit0/Awesome-CV#32]
CVHeader gives the following error

```
! Package etoolbox Error: Boolean '\ifistart' undefined.

See the etoolbox package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.114 \makecvheader
```

Commenting out `\makecvheader`, then compiling, then uncommenting `\makecvheader` and again compiling works.

**Comment by johannesbottcher** [comment]
Silly thing, almost all conditionals in the header are missing an s. An updated version will be available within the next days, a week max. 

@posquit0  I will be busy within the next few days. I hope you can adress this earlier, if not expect a PR for the weekend.

**Comment by nipunbatra** [comment]
Created a PR: https://github.com/posquit0/Awesome-CV/pull/33

Many thanks for the `awesome` work!

**Comment by posquit0** [comment]
OMG... I've not noticed about this typing error! Thanks so much @nipunbatra

@johannesbottcher Thanks for your contributions :+1:

**Comment by thedch** [comment]
Very late comment here, but I'm also having this issue...

```
Package etoolbox Error: Boolean '\ifistart' undefined. See the etoolbox package documentation for explanation. Type H <return> for immediate help. ... 

l.49 \makecvheader```

But when I go to the definition of `\makecvheader`, I can't find any reference to a `\ifistart` (or anywhere else in the entire codebase), so I don't know where I could define it so it can be properly used.

Here's the beginning of the fxn:

```
% Usage: \makecvheader
\newcommand*{\makecvheader}{
  \begin{center}
    \headerfirstnamestyle{
      \@firstname
    } \headerlastnamestyle{
      \@lastname
    }
    \\
    \vspace{0.4mm}
    \ifthenelse{\isundefined{\@position}}{}{\headerpositionstyle{\@position\\}}
    \vspace{0.4mm}
    \ifthenelse{\isundefined{\@address}}{}{\headeraddressstyle{\@address\\}}
    \vspace{-0.5mm}
    \headersocialstyle{
      \newbool{isstart}
      \setbool{isstart}{true}
      \ifthenelse{\isundefined{\@mobile}}
        {}
        {
           \@mobile
          \setbool{isstart}{false}
        }
      \ifthenelse{\isundefined{\@email}}
```

Any ideas? Thanks (I'm using Overleaf)
