### ISSUE TITLE
[Question] How do I left align the cvskill section

### ISSUE THREAD

**Issue by Noobzik** [posquit0/Awesome-CV#320]
I want to align the first section (in bold in picture below) to the left.
This section is part of the \cvskill and I don't know how to do it.

![image](https://user-images.githubusercontent.com/3254621/75275608-180ff080-5805-11ea-9636-445eb8b01b22.png)

**Comment by RohitBanga3** [comment]
use this 
\newenvironment{cvskills}{%
  \vspace{\acvSectionContentTopSkip}
  \vspace{-2.0mm}
  \begin{center}
    \setlength\tabcolsep{0.2ex}
    \setlength{\extrarowheight}{0pt}
    \begin{tabular*}{\textwidth}{@{\extracolsep{\fill}} l L{\textwidth * \real{0.9}}}
}{%
    \end{tabular*}
  \end{center}
it worked for me
