### ISSUE TITLE
In cventry, have organization and date in the same line

### ISSUE THREAD

**Issue by umerf52** [posquit0/Awesome-CV#323]
Hello.   
I'm trying to use the template but facing a minor issue.
For for certain ````cventry````, I want to leave the position and location blank but it rather looks ugly. See below:
![image](https://user-images.githubusercontent.com/20578979/76428143-19c5e080-63cf-11ea-9180-12b562afb3b5.png)
How do I make organization and date appear in the same line, if job title and location are left empty?

**Comment by sabdulm** [comment]
Change the definition for cventry in [line 598 of the awesome-cv.cls](https://github.com/posquit0/Awesome-CV/blob/4be6c213c8631a1fd68d1ad452e88b722b911f78/awesome-cv.cls#L598) of the  to the one below. Commented the old def, with new ones according to your needs above it.

`% Define an entry of cv information`
`% Usage: \cventry{<position>}{<title>}{<location>}{<date>}{<description>}`
`\newcommand*{\cventry}[5]{%`
`  \vspace{-2.0mm}`
`  \setlength\tabcolsep{0pt}`
`  \setlength{\extrarowheight}{0pt}`
`  \begin{tabular*}{\textwidth}{@{\extracolsep{\fill}} L{\textwidth - 4.5cm} R{4.5cm}}`
`    \ifempty{#1#3}`      **_added this_**
`      {\entrytitlestyle{#2} & \entrydatestyle{#4} \\}`   **_added this_**
`      {\entrytitlestyle{#2} & \entrylocationstyle{#3} \\`   **_added this_**
 `     \entrypositionstyle{#1} & \entrydatestyle{#4} \\}`   **_added this_**
`    % \ifempty{#2#3} ` **_commented this_**
`    %   {\entrypositionstyle{#1} & \entrydatestyle{#4} \\}` **_commented this_**
`    %   {\entrytitlestyle{#2} & \entrylocationstyle{#3} \\` **_commented this_**
`    %   \entrypositionstyle{#1} & \entrydatestyle{#4} \\}` **_commented this_**
`    \multicolumn{2}{L{\textwidth}}{\descriptionstyle{#5}}`
`  \end{tabular*}%`
`}`

Hope that was what you meant by your issue

**Comment by umerf52** [comment]
Thanks! Exactly what I was looking for!
