### ISSUE TITLE
Project maintenance?

### ISSUE THREAD

**Issue by cxkoda** [posquit0/Awesome-CV#324]
It seems like this project is no longer maintained. The last commit on master is over half a year old and there are 70 open pull requests with mostly little to no feedback by the maintainers even though the community is quite active.

It would be interested to hear how you (@posquit0) are planning to continue in the future. Are you looking for other co-maintainers? Or are you thinking to drop it completely? Should the community just fork it and independently move on from there?

**Comment by mbuet2ner** [comment]
I think it might be best to just fork it- given there are people that are willing to invest time in maintaining the project. 
Of course, it would be great if @posquit0 would say something. However, telling from the past this is unlikely.

Forking is the FOSS spirit after all! :star2:

**Comment by janmayer** [comment]
The LPPL license is specified in the `awesome-cv.cls` class itself.

This license ist unfortunately not as free as the MIT Licence, but actually has clauses for change of maintainer.

**Comment by OJFord** [comment]
Namely:

> The Work changes from status 'maintained' to 'unmaintained' if there is no Current Maintainer, or the person stated to be Current Maintainer of the work cannot be reached through the indicated means of communication for a period of six months, and there are no other significant signs of active maintenance.

> You can become the Current Maintainer of the Work by agreement with any existing Current Maintainer to take over this role.

> If the Work is unmaintained, you can become the Current Maintainer of the Work through the following steps:

> 1.    Make a reasonable attempt to trace the Current Maintainer (and the Copyright Holder, if the two differ) through the means of an Internet or similar search.
> 2.    If this search is successful, then enquire whether the Work is still maintained.
>     1. [sic, 2a]   If it is being maintained, then ask the Current Maintainer to update their communication data within one month.
>     2. [sic, 2b]   If the search is unsuccessful or no action to resume active maintenance is taken by the Current Maintainer, then announce within the pertinent community your intention to take over maintenance. (If the Work is a LaTeX work, this could be done, for example, by posting to comp.text.tex.)
> 3.    [something here for GH formatting]
>     1. [sic, 3a]   If the Current Maintainer is reachable and agrees to pass maintenance of the Work to you, then this takes effect immediately upon announcement.
>     2. [sic, 3b]   If the Current Maintainer is not reachable and the Copyright Holder agrees that maintenance of the Work be passed to you, then this takes effect immediately upon announcement.
> 4.    If you make an `intention announcement’ as described in 2b. above and after three months your intention is challenged neither by the Current Maintainer nor by the Copyright Holder nor by other people, then you may arrange for the Work to be changed so as to name you as the (new) Current Maintainer.
> 5.    If the previously unreachable Current Maintainer becomes reachable once more within three months of a change completed under the terms of 3b) or 4), then that Current Maintainer must become or remain the Current Maintainer upon request provided they then update their communication data within one month.

> A change in the Current Maintainer does not, of itself, alter the fact that the Work is distributed under the LPPL license.

> If you become the Current Maintainer of the Work, you should immediately provide, within the Work, a prominent and unambiguous statement of your status as Current Maintainer. You should also announce your new status to the same pertinent community as in 2b) above.

http://www.latex-project.org/lppl

---

I have created a GH org called 'awesomecv' ('awesome-cv' is unfortunately an unrelated username) as somewhere people's various unmerged (here) fixes and improvements can congregate. There's loads of personal forks already of course, including my own, but none (correct me if I'm wrong) that seems to have made continual progress or attracted other contributors - hoping that an appropriately named org can be a new somewhat centralised home. Open to any collaborators, (@cxkoda, you sound willing? 🙂) not least because of the risk of the same just happening again, but most importantly PRs from personal forks or that are just gathering dust here.

@posquit0 - per 2b above, please respond if you have any intention of continuing maintenance of the Awesome CV project, or a preferred way for it to continue without you - you could add me or any other volunteers as collaborators on the repository while still under your own user namespace, for example - by 2022/02/08. If I don't hear anything, I'll include a note in the readme on history linking back to this repo/issue, and encourage PR authors here to re-open against the new one.

**Comment by cxkoda** [comment]
Awesome! Great to see someone picking it up again. Thanks @OJFord! Unfortunately, I can't help out in the foreseeable future because I'm a bit swamped with work... I wish you all the best with the project!

**Comment by posquit0** [comment]
@OJFord @cxkoda Sorry for late reply. And sorry to everyone who loves awesome-cv.

In recent years, I've been busy building products in early-stage startups.
This led me to move away from this project.

Around February of next year, I think I will be able to invest time in project maintenance again.
First of all, I've given @OJFord permission as a collaborator.
Thanks for your help and interest for this project.

Please message me if you need my opinion. :)

**Comment by OJFord** [comment]
Good to hear from you @posquit0! This is surely everyone's preferred outcome 🙂.

Can confirm I've received (and accepted) your invitation, as I suppose a badge will now show just there ^ or so. I'll start on a bit of issue triage later today.

And, er, closing this issue as 'yes, being maintained'! 🤞🏻
