### ISSUE TITLE
skill section different alignment

### ISSUE THREAD

**Issue by segalinc** [posquit0/Awesome-CV#325]
I would like to change the skill session so that the type is on the right and the skill entry is on the left and so that the left columns is aligned to the left and the type aligned to the very right 
like in the picture 

<img width="465" alt="Screen Shot 2020-04-10 at 5 24 07 PM" src="https://user-images.githubusercontent.com/9353106/79030990-c4592c80-7b50-11ea-9bc2-94cf090668c8.png">

I almost managed to do it but as you see the right column gets squished and some works return in a new line

I changed this line in the skill class 
    \begin{tabular*}{\textwidth}{@{\extracolsep{\fill}} l R {0.1\textwidth}}

how can I change it so that the type stays in one line ?

**Comment by segalinc** [comment]
almost there with this code but now the next session is too close to the end of the previous

\newenvironment{cvskills}{%
  \vspace{\acvSectionContentTopSkip}
  \vspace{-2.0mm}
    \setlength\tabcolsep{1ex}
    \setlength{\extrarowheight}{0pt}
    \begin{tabular*}{\textwidth}{@{\extracolsep{\fill}} l R {.3\textwidth}}
}{%
    \end{tabular*}
  \vspace{\acvSectionContentTopSkip}
}

**Comment by segalinc** [comment]
almost there but if the left line is too long it goes out of the sheet

\newenvironment{cvskills}{%
  \vspace{\acvSectionContentTopSkip}
  \vspace{-2.0mm}
  \begin{flushleft}
    \setlength\tabcolsep{1ex}
    \setlength{\extrarowheight}{0pt}
    \begin{tabular*}{.9\textwidth}{@{\extracolsep{\fill}} l R {.2\textwidth}}
}{%
    \end{tabular*}
  \end{flushleft}
}

**Comment by dcsim** [comment]
![Screenshot_20211222_214111](https://user-images.githubusercontent.com/1300336/147184663-f2c2d852-26d3-4182-a671-d11feb6c0313.png)

These are the necessary changes to make in `awesome-cv.cls`:

> % Define an environment for cvskill
> \newenvironment{cvskills}{%
>   \vspace{\acvSectionContentTopSkip}
>   \vspace{-2.0mm}
>   \begin{center}
>     \setlength\tabcolsep{1ex}
>     \setlength{\extrarowheight}{0pt}
>     \begin{tabular*}{\textwidth}{@{\extracolsep{\fill}} L{\textwidth -{4.5cm}} r} %Changed this
> }{%
>     \end{tabular*}
>   \end{center}
> }
> % Define a line of cv information(skill)
> % Usage: \cvskill{<type>}{<skillset>}
> \newcommand*{\cvskill}[2]{%
>   \skillsetstyle{#2} & \skilltypestyle{#1} \\ %Changed this
> }

**Comment by OJFord** [comment]
Thanks @dcsim!
