### ISSUE TITLE
How can include signature.png in bottom left in CV & cover letter?

### ISSUE THREAD

**Issue by clevilll** [posquit0/Awesome-CV#334]
I was wondering if I include my signature picture at the end of the CV & cover letter.

**Comment by tobiaslombacher** [comment]
You can use the following code: 

`\letterclosing{Best Regards,\\\includegraphics[height=15mm]{signature.png}}`

I have used this on the cover letter. On the CV you should be able to do something similar.

The signature file has to be in the root directory where the cv.tex file is. Alternatively, you have to specify the path.
