### ISSUE TITLE
Rmd files for cover letter 

### ISSUE THREAD

**Issue by amanas** [posquit0/Awesome-CV#337]
Sorry, this is not an issue, but do not really know how to contact.

Is it possible to generate this awesome cover letter with Rmarkdown? Would you have an example?

Thanks.

**Comment by OJFord** [comment]
I haven't heard of [Rmarkdown](https://bookdown.org/yihui/rmarkdown/pdf-document.html#latex-options) before, but it does seem to have Latex options. Awesome-CV is just a latex class, so it's just down to whether it'll let you import it appropriately I suppose. Better to ask Rmarkdown support channels if you have any trouble, it's not really Awesome-CV specific.
