### ISSUE TITLE
How to replace the tabular in \cvhonors with longtable?

### ISSUE THREAD

**Issue by BBge** [posquit0/Awesome-CV#341]
\newenvironment{cvhonors}{%
  \vspace{\acvSectionContentTopSkip}
  \vspace{-2mm}
  \begin{center}
    \setlength\tabcolsep{0pt}
    \setlength{\extrarowheight}{0pt}
    \begin{tabular*}{\textwidth}{@{\extracolsep{\fill}} C{0.5cm} L{\textwidth - 3cm} R{3cm}}
}{%
    \end{tabular*}
  \end{center}
}

I want to change the tabular to longtable.
But it has some problems as shown in the following figure.
![image](https://user-images.githubusercontent.com/18453645/94752726-07ef5f00-035a-11eb-9e2f-ef04ccdc1f2b.png)

**Comment by OJFord** [comment]
Closing to keep #331 as the canonical issue for this.
