### ISSUE TITLE
It requires to install fontawesome packages.

### ISSUE THREAD

**Issue by wanyaworld** [posquit0/Awesome-CV#346]
[https://www.reddit.com/r/LaTeX/comments/cuzny7/miktex_297100_unable_to_find_or_download/](a)

As muedominik pointed out in the link above, one needs to install fontawesome packages by following commands.
(Not sure it both of two are required)

```
mpm --install=fontawesome
mpm --install=fontawesome5
```

**Comment by thiagoveloso** [comment]
On a macOS system, all you need is download the file at https://github.com/FortAwesome/Font-Awesome/blob/v4.7.0/fonts/FontAwesome.otf and install it with the `Font Book ` app.

**Comment by paxperscientiam** [comment]
@thiagoveloso thanks dude. this is the way. IDKW, but distro's fontawesome file wasn't used. Honestly, not worth the hassle to figure out since this works.

**Comment by OJFord** [comment]
Closed via #344, this shouldn't be necessary.
