### ISSUE TITLE
Highlight in \cventry cvitems

### ISSUE THREAD

**Issue by minsung-k** [posquit0/Awesome-CV#347]
Hi, I want to highlight only some specific words in cvitems like italic or underline.

Is anyone know how to do it?

**Comment by eosti** [comment]
The subfiles that are imported into the main resume.tex/coverletter.tex/cv.tex files still have all of the standard LaTeX formatting available. For italics, use `\emph{Some text here}` and for underline use `\underline{Some other text here}`.

**Comment by dcsim** [comment]
@OJFord: This was answered and might be ready to close.
