### ISSUE TITLE
Top alignment cvskills section 

### ISSUE THREAD

**Issue by SmarithLogic** [posquit0/Awesome-CV#351]
Hello, in the skills section of awesome cv I have several lines concerning an item. However, the alignment is central whereas I would like it to be at the top. I have seen on other problems that the letter L has to be replaced by K but it doesn't work and doesn't show the expected result. 

Here is what I would like to do!

![Capture](https://user-images.githubusercontent.com/69488283/99889061-2d119700-2c52-11eb-9af0-4483d7c05e6e.PNG)

Thank you in advance for your reply,

**Comment by asan-emirsaleh** [comment]
Hello @SmarithLogic 
How did you solved this problem?
I try to use top alignment rule with [t] in position before column statement description. But it brakes the design.
`\begin{tabular*}[t]{\textwidth}{@{\extracolsep{\fill}} l L{\textwidth * \real{0.8}}}
}{%
    \end{tabular*}`
