### ISSUE TITLE
Missing \begin{document}

### ISSUE THREAD

**Issue by Yahyakiani** [posquit0/Awesome-CV#352]
When i try to convert my tex file to pdf using xelatex command I get this error. Missing \begin{document}.
I am testing it on windows using MIKTEX console.Tried on the recommended website as well but it still breaks.
Wondering if you could point me in the right direction.
Thanks

**Comment by juansamdphd** [comment]
Hi there! How did you solve this issue? I've started to get the same error as well.

**Comment by Yahyakiani** [comment]
I used docker to solve this issue.There is a docker image for this project on Docker repo.Use that to create the environment and then mount your directory which contains your file  for conversion.After that just execute the makefile and it will compile with errors but successfully with an output file.

**Comment by Hatzen** [comment]
I got the exact same problem with MikTex 

```
PS C:\cv\examples> xelatex cv.tex
This is XeTeX, Version 3.141592653-2.6-0.999993 (MiKTeX 22.1) (preloaded format=xelatex.fmt)
 restricted \write18 enabled.
entering extended mode
(cv.tex
LaTeX2e <2021-11-15> patch level 1
L3 programming layer <2022-02-05> (awesome-cv.cls

! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.1 .
     ./awesome-cv.cls
?
Missing character: There is no . in font nullfont!
Missing character: There is no . in font nullfont!
```

but also when trying to run the docker image on WSL

```
hatzen@LAPTOP-XYZ:~/cv/Awesome-CV-master$ docker run --rm --user $(id -u):$(id -g) -i -w "/doc" -v "$PWD":/doc thomasweise/texlive make
Welcome to the TeX Live docker container thomasweise/texlive.
GitHub   : http://www.github.com/thomasWeise/docker-texlive
DockerHub: http://hub.docker.com/r/thomasweise/texlive
The command 'make' with arguments '' was specified. Now executing this command.
xelatex -output-directory=examples examples/coverletter.tex
This is XeTeX, Version 3.14159265-2.6-0.999992 (TeX Live 2020/Debian) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
(./examples/coverletter.tex
LaTeX2e <2020-02-02> patch level 5
L3 programming layer <2020-06-18> (examples/awesome-cv.cls

! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.1 .
     ./awesome-cv.cls
?
)
Overfull \hbox (20.0pt too wide) in paragraph at lines 1--22
....
```

So  i guess this issue should not be closed..

**Comment by matt115** [comment]
> I got the exact same problem with MikTex
> 
> ```
> PS C:\cv\examples> xelatex cv.tex
> This is XeTeX, Version 3.141592653-2.6-0.999993 (MiKTeX 22.1) (preloaded format=xelatex.fmt)
>  restricted \write18 enabled.
> entering extended mode
> (cv.tex
> LaTeX2e <2021-11-15> patch level 1
> L3 programming layer <2022-02-05> (awesome-cv.cls
> 
> ! LaTeX Error: Missing \begin{document}.
> 
> See the LaTeX manual or LaTeX Companion for explanation.
> Type  H <return>  for immediate help.
>  ...
> 
> l.1 .
>      ./awesome-cv.cls
> ?
> Missing character: There is no . in font nullfont!
> Missing character: There is no . in font nullfont!
> ```
> 
> but also when trying to run the docker image on WSL
> 
> ```
> hatzen@LAPTOP-XYZ:~/cv/Awesome-CV-master$ docker run --rm --user $(id -u):$(id -g) -i -w "/doc" -v "$PWD":/doc thomasweise/texlive make
> Welcome to the TeX Live docker container thomasweise/texlive.
> GitHub   : http://www.github.com/thomasWeise/docker-texlive
> DockerHub: http://hub.docker.com/r/thomasweise/texlive
> The command 'make' with arguments '' was specified. Now executing this command.
> xelatex -output-directory=examples examples/coverletter.tex
> This is XeTeX, Version 3.14159265-2.6-0.999992 (TeX Live 2020/Debian) (preloaded format=xelatex)
>  restricted \write18 enabled.
> entering extended mode
> (./examples/coverletter.tex
> LaTeX2e <2020-02-02> patch level 5
> L3 programming layer <2020-06-18> (examples/awesome-cv.cls
> 
> ! LaTeX Error: Missing \begin{document}.
> 
> See the LaTeX manual or LaTeX Companion for explanation.
> Type  H <return>  for immediate help.
>  ...
> 
> l.1 .
>      ./awesome-cv.cls
> ?
> )
> Overfull \hbox (20.0pt too wide) in paragraph at lines 1--22
> ....
> ```
> 
> So i guess this issue should not be closed..

Actually working  for me; just copied the awesome-cv.cls from the root to the examples directory. Then used MiKTeX container so I dont have to manage all deps. (  https://hub.docker.com/r/miktex/miktex )
