### ISSUE TITLE
Open github/linkedin/protfolio link in a new tab 

### ISSUE THREAD

**Issue by Sed9yDataBank** [posquit0/Awesome-CV#356]
how to open these in a new tab on click in resume.tex? 
\homepage{mylinkwhatever}
\github{username}
\linkedin{mylinkwheatever}

**Comment by OJFord** [comment]
I don't think it's possible - they're essentially just `\href{url}{logo & description}`s, I don't think a PDF can tell the browser how to open a link, nevermind how that might be achieved in latex.
