### ISSUE TITLE
CircleCI pipe failing

### ISSUE THREAD

**Issue by anthonytwh** [posquit0/Awesome-CV#365]
https://app.circleci.com/pipelines/github/posquit0/Awesome-CV

  <a href="https://circleci.com/gh/posquit0/Awesome-CV">
    <img alt="CircleCI" src="https://circleci.com/gh/posquit0/Awesome-CV.svg?style=shield" />
  </a>

 - Makefile is missing fontawesome.sty import

**Comment by OJFord** [comment]
(cf. https://github.com/posquit0/Awesome-CV/pull/366#issuecomment-965632314)
