### ISSUE TITLE
How can I customize font style here?

### ISSUE THREAD

**Issue by williamxu7** [posquit0/Awesome-CV#369]
Hello, I am quite new to Overleaf. Really like this template. I wanted to customize font style, anyone knows how? Thanks in advance.

**Comment by greeksachdeva** [comment]
Did you get the solution on how to customize the font?

**Comment by OJFord** [comment]
From what I recall, Overleaf has some decent docs & tutorials on general latex things like this - check there, or search tex.stackexchange.com.

Closing as unrelated to Awesome-CV.
