### ISSUE TITLE
asking for sub_cvitems on cventry

### ISSUE THREAD

**Issue by fadamsyah** [posquit0/Awesome-CV#370]
Hello. I really appreciate this work, and thank you for making the repository public.

Is anyone here know how to insert a sub_cvitems inside the cvitems? I want to make a list inside a list on my experience section.

Thanks in advance!

**Comment by Apoorb** [comment]
You can use *itemize* to add list inside a list. Following is an example from my CV: 

>     
    {
      \begin{cvitems} % Description(s) of tasks/responsibilities
        \item {\BoldText{Guidelines for Semi-Autonomous Truck Operation in Texas} \emphLanguage{C++, R: data.table, ggplot2}}
        \begin{itemize}
            \item {Designed a full factorial simulation experiment for evaluating the impact of truck platooning (trucks following each other closely) with automated driving support systems on traffic operations.}
            \item {Established guidelines about the conditions in which truck platooning should be allowed.}
        \end{itemize}
       \item {\BoldText{New Approaches for Testing Connected Highway and Vehicle Systems} \emphLanguage{C++, R}}
        \begin{itemize}
            \item {Developed component to enable interaction between a connected vehicle, traffic signal controller, and simulation software.}
        \end{itemize}
      \end{cvitems}
    }

**Comment by fadamsyah** [comment]
Great! Thank you very much for your help.
