### ISSUE TITLE
I want to to print linked, github name insted of whole link on pdf. How can I do it?

### ISSUE THREAD

**Issue by s0sharma** [posquit0/Awesome-CV#371]

**Comment by OJFord** [comment]
`\github{s0sharma}` should render `<gh icon> s0sharma` with a clickable link to `https://github.com/s0sharma`.

Is that not what you're seeing?

**Comment by OJFord** [comment]
This works as expected on my own CV, so closing for now - feel free to ping me/reopen if it's not working as described above for you though.
