### ISSUE TITLE
ResearchGate account

### ISSUE THREAD

**Issue by Nour002** [posquit0/Awesome-CV#379]
I'm trying to add my research gate account to my CV, but every time I run into this error (also the logo doesn't appear, but I can still click on my name and it takes me to the right page).

```
The compiler is having trouble understanding a command you have used. Check that the command is spelled correctly. If the command is part of a package, make sure you have included the package in your preamble using \usepackage{...}.
Learn more
<argument> \faresearchgate 
                           \acvHeaderIconSep \@researchgate 
l.81 
     
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.
```

This is how I defined it:

```
% Defines writer's researchgate (optional)
% Usage: \researchgate{<researchgate account>}
\newcommand*{\researchgate}[1]{\def\@researchgate{#1}}
```
```
  \ifthenelse{\isundefined{\@researchgate}}%
        {}%
        {%
          \ifbool{isstart}{\setbool{isstart}{false}}{\acvHeaderSocialSep}%
          \href{https://www.researchgate.net/profile/\@researchgate}{\faresearchgate\acvHeaderIconSep\@researchgate}%
        }%
```

**Comment by OJFord** [comment]
Where did you put that `\ifthenelse`? I think I see where you copied/modified it from - but you can't just put that at your top level after importing awesomecv.cls for example.

You could do something like this:
```latex
\newcommand{\researchgate}[1]{
  \extrainfo{\href{https://researchgate.net/profile/#1}{\faResearchgate\acvHeaderIconSep#1}}
}
```

Or you could modify awesomecv.cls to add it much as you have above along with the others. (And if you do that, please open a PR 🙂.)

**Comment by awsaf49** [comment]
@OJFord Hi, when I'm trying to extra link like Researchgate it does't have an icon like I have for **GitHub** for **Twitter**. Is there any way to add icons for them?

**Comment by OJFord** [comment]
@awsaf49 In 444f0db I added a `\researchgate` that uses [the ResearchGate icon from FontAwesome](https://fontawesome.com/v5.15/icons/researchgate) - is that not working for you?

If you're using `\extrainfo` it indeed won't have an icon - use `\researchgate` instead.

If you're using `\researchgate` and it isn't working, please open a new issue about that.

**Comment by awsaf49** [comment]
@OJFord actually I was trying to add `\kaggle` command, [Kaggle](https://www.kaggle.com) is quite popular for **Data Science**. I have added the command but can't seem to figure out how to add an icon for it.

**Comment by OJFord** [comment]
`\faKaggle` [should work](https://fontawesome.com/v5.15/icons/kaggle), if you open a PR with what you have I can have a look and try to help there.

**Comment by awsaf49** [comment]
Okay, I'll start a **PR** then shortly
