### ISSUE TITLE
Issue on extracting plain text

### ISSUE THREAD

**Issue by torabkheslat** [posquit0/Awesome-CV#386]
Dears

I faced Issue when extracting text from PDF:

for example 

SOFTWARE ARCHiTECT
CO‐FOUNDER & SOFTWARE ENGiNEER
SOFTWARE ENGiNEER & SECURiTY RESEARCHER (COMPULSORY MiLiTARY SERViCE)
GAME DEVELOPER INTERN AT GLOBAL INTERNSHiP PROGRAM

**Comment by OJFord** [comment]
This is _potentially_ solvable by ensuring a sensible 'text layer' in the rendered PDFs (I don't know much about this) - but:
- AwesomeCV makes no claim to do that, or to be anything other than human readable;
- sounds like you're doing something with candidates' CVs that they wouldn't expect/want anyway, so doesn't seem a compelling feature.
