### ISSUE TITLE
cventry 3rd and 4th arguments do not display Cyrillic symbols

### ISSUE THREAD

**Issue by kdarkhan** [posquit0/Awesome-CV#39]
Probably it is a problem with the font used to display it. In other places, Cyrillic symbols appear properly
but in cventries, arguments used to display dates and cities show up as boxes in pdf.

**Comment by johannesbottcher** [comment]
At least i need a compilable minimal example to reproduce your issue.

**Comment by kdarkhan** [comment]
I modified experience.tex from the sample and added Cyrillic symbols

```latex
\cvsection{Experience}
\begin{cventries}
  \cventry
    {Job title Должность} % Job title
    {Organization Организация} % Organization
    {Cyrillic Location Место} % Location
    {Date Cyrillic Дата} % Date(s)
    {
      \begin{cvitems} % Description(s) of tasks/responsibilities
        \item {CVITem Cyrillic Пункт}
      \end{cvitems}
    }
\end{cventries}
```
It produces the following output. Cyrillic symbols in `\entrylocationstyle` and `\entrydatestyle` show up as boxes.
![screenshot from 2016-03-26 18-54-33](https://cloud.githubusercontent.com/assets/1087493/14060150/9664bed2-f384-11e5-8a3f-3566e4b7a4e0.png)

**Comment by johannesbottcher** [comment]
The font used does not contain cyrillic letters. Simple as that. Do `\newfontfamily\bodyfontlight{Linux Biolinum O}` right before `\begin{document}`. Instead of Biolinum, you can use any font you like that contains the glyphs needed.

**Comment by kdarkhan** [comment]
Thanks
