### ISSUE TITLE
wonky sub items

### ISSUE THREAD

**Issue by mrethabile** [posquit0/Awesome-CV#391]
I'm not sure if I am doing something off or I missed a point but sub items are wonky either as `cvitems` or `itemize`.

To reproduce, first as `cvitems`:

```tex
%-------------------------------------------------------------------------------
%	SECTION TITLE
%-------------------------------------------------------------------------------
\cvsection{Experience}

%-------------------------------------------------------------------------------
%	CONTENT
%-------------------------------------------------------------------------------
\begin{cventries}
    \cventry
        {Senior Developer} % Job title
        {Awesome Company Pty Ltd} % Organization
        {California} % Location
        {Sep. 2019 - Current} % Date(s)
        { 
        \begin{cvitems} % Description(s) of tasks/responsibilities
            \item {Full stack in .NET and JavaScript}
            \item {Build and integrate new web applications}
            \item {Fix bugs and all sort of issues
                \begin{cvitems}
                    \item {Code issues, anywhere from front-end to server-side}       
                    \item {Database issues (query performance, jobs, maintenance)}
                    \item {Service issues (services downtime)}
                \end{cvitems}}
        \end{cvitems}
        }
\end{cventries}
```
Result:

![snip0](https://user-images.githubusercontent.com/97121730/148121885-b2f95088-f4de-4a90-a4ec-8e995cc03ec6.jpg)

as `itemize`:
```tex
%-------------------------------------------------------------------------------
%	SECTION TITLE
%-------------------------------------------------------------------------------
\cvsection{Experience}

%-------------------------------------------------------------------------------
%	CONTENT
%-------------------------------------------------------------------------------
\begin{cventries}
    \cventry
        {Senior Developer} % Job title
        {Awesome Company Pty Ltd} % Organization
        {California} % Location
        {Sep. 2019 - Current} % Date(s)
        { 
        \begin{itemize} % Description(s) of tasks/responsibilities
            \item {Full stack in .NET and JavaScript}
            \item {Build and integrate new web applications}
            \item {Fix bugs and all sort of issues
                \begin{cvitems}
                    \item {Code issues, anywhere from front-end to server-side}       
                    \item {Database issues (query performance, jobs, maintenance)}
                    \item {Service issues (services downtime)}
                \end{itemize}}
        \end{cvitems}
        }
\end{cventries}
```
Result: while not squashed, but the tab looks extra ordinary,

![snip1](https://user-images.githubusercontent.com/97121730/148122223-7d0859b1-c9d8-4667-a217-fb624f68bc66.jpg)

**Comment by dcsim** [comment]
Below isn't necessarily a _good_ way to do what you're trying to do, but it works. Change `--` to `---` if you'd prefer an em dash.

```
 \item {Designed an overall service architecture and pipelines of: \\%
      \quad -- the Machine Learning based Fashion Tagging API SaaS product \\%
      \quad -- with the micro-services architecture.}
```

![Sub Items](https://user-images.githubusercontent.com/1300336/149454568-81ffbd5f-31b0-4fef-87e5-1c60d12b517a.png)


Below is another way to do what you want, although it isn't necessarily a _good_ way to do it, but again it works. The `\\` may not be necessary if subitem isn't for an item in the middle of the list. I didn't bother to check. Slightly different output then the first option.

```
        \item {Designed an overall service architecture and pipelines of: \\
          \begin{cvitems}
              \item {the Machine Learning based Fashion Tagging API SaaS product}
              \item {with the micro-services architecture.\\}
          \end{cvitems}
        }
```

![Sub Items 2](https://user-images.githubusercontent.com/1300336/149454600-c79dab68-21a6-4dee-969b-2f085ca77025.png)

**Comment by mrethabile** [comment]
I can try that. but since you are mentioning that's not necessarily a good way I would guess it's a workaround.

So after browsing the `.cls` source I found out that the `cvitems` comes with a vspace of -4mm i.e. `vspace{-4.0mm}`. If I counter-offer that, then the issue cancel.

```
        \item {Fix bugs and all sort of issues
        \vspace{4.0mm}
        \begin{cvitems} % Description(s) of tasks/responsibilities
          \item {Code issues, anywhere from front-end to server-side}       
          \item {Database issues (query performance, jobs, maintenance)}
          \item {Deployment gone wrong}
          \item {Service issues (services downtime)}
          \item {Server issues (scheduled, unscheduled maintenance)}
        \end{cvitems}}
``` 
![snip02](https://user-images.githubusercontent.com/97121730/149468389-2c9028d7-9f25-42f7-aceb-2d904550542a.jpg)

**Comment by dcsim** [comment]
I think all three of these solutions are workarounds, because I don't think the class file intends for items under entries to have subitems. 

Your `vspace` solution is a good workaround and looks well suited for your use case. If others are looking for a similar way to accomplish this in the future, it would be a good place to start.

I specifically mention that my solutions aren't "good" because throwing `\\` around isn't always a good idea, but in this situation they "work."

**Comment by rehanguha** [comment]
If we take a situation where I got promoted at a same company and hold 2 designation. I will prefer to have a single entry with sub items(like LinkedIn) rather than two different entries.
Is there any way to achieve that?

**Comment by dcsim** [comment]
@rehanguha: I think there have been a few issue threads related to spacing issues in `cvsubentries` that might be helpful. You might find solutions to making the existing `cvsubentries` work better and resolve the spacing issues in those. 

My (private) fork has the following command to allow for multiple positions within the same company. It may or not look like what you're hoping for.

I have modified the command here so it will use Awesome-CV fonts:

Added to the class file between `cventry` and `cvsubentries`
```
% Define Multiple Positions with a Single Company
% Use: \cventrymultiposition{<Organization>}{Total Dates}{<Position>}{<date>}{previous position}{old date}{...}{n...}{<description>}; adjust params as need.
% Note: specifying a negative skip after a line using glue following the terminator appears to solve the spacing issue in cventry.
\newcommand*{\cventrymulti}[9]{%
  \setlength\tabcolsep{0pt}
  \setlength{\extrarowheight}{0pt}
  \begin{tabular*}{\textwidth}{@{\extracolsep{\fill}} L{\textwidth - 4.0cm} R{4.0cm}}
    \ifempty{#7#8} 
      {\entrytitlestyle{#1} & \entrydatestyle{#2} \\[-0.5cm]%
      \entrypositionstyle{#3} & \entrylocationstyle{#4}  \\[-0.05cm]
      \entrypositionstyle{#5} & \entrylocationstyle{#6} \\}
      {\entrytitlestyle{#1} & \entrydatestyle{#2} \\[-0.05cm]
      \entrypositionstyle{#3} & \entrydatestyle{#4}  \\[-0.05cm]
      \entrypositionstyle{#5} & \entrydatestyle{#6} \\[-0.05cm]
      \entrypositionstyle{#7} & \entrydatestyle{#8} \\} 
      \if\relax\detokenize{#9}\relax\else
        \multicolumn{2}{L{\textwidth}}{\descriptionstyle{#9}}
      \fi
  \end{tabular*}%
}
```

Usage in the `experience.tex` file. Note the order is different from the usual Awesome-CV entry.

```
  \cventrymulti
    {Huge Law Firm} % Job title
    {Jun. '15 - Present} % Organization
    {Managing Attorney} % Location
    {Feb. 2021 - Present} % Date(s)
    {Attorney}
    {Oct. 2017 - Jan. 2021}
    {Law Clerk}
    {Jun. '15 - Sep. 2017}
    {
      \begin{cvitems} % Description(s) of tasks/responsibilities
        \item {Attorney stuff. Writing stuff. Negotiating stuff.}
        \item {Supervisory stuff. Managing, delegating, reviewing, recruiting. That kind of stuff.}
        \item {Stuff Stuff Stuff.}
      \end{cvitems}
    }
```

Using already defined Awesome-CV fonts the output is:

![multi position](https://user-images.githubusercontent.com/1300336/149669824-f6ce9106-f70a-48b1-b08d-6f80bd7fa132.png)


I'm not sure which of the existing Awesome-CV font definitions should be used in the command to make it look more "Awesome-CV" and it is possible that you'd need to add additional fonts definitions.

Below is what the output the `cventrymulti` looks like as I use it. I hope it provides additional context on what font choices may be helpful.

![multipos demo](https://user-images.githubusercontent.com/1300336/149670251-94df56a7-bd7a-4150-8098-e4a378c2460e.png)

**Comment by rehanguha** [comment]
@dcsim  Thank you for the response.  I have already found a work around and it kind of works fine.

```
\cventry
{Job title after promotion} % Job title
{Corporation} % Organization
{Location} % Location
{August 2019 - now}
{
  \begin{cvitems} 
	\item {Responsibilities}
	\end{cvitems}
 }


\cventry
{Job title before your promotion}
{} % Organization EMPTY
{} % Location EMPTY
{somewhere in the past - a while ago} % Date(s)
{
  \begin{cvitems}
	\item {Old responsibilities}
	\end{cvitems}
 }
```

![image](https://user-images.githubusercontent.com/16112670/149763213-977d1827-09b3-4113-81cb-918dc4816579.png)


Got the solution @ https://github.com/posquit0/Awesome-CV/issues/297

This kind off solved my need, Thank you again for the time.

**Comment by dcsim** [comment]
@OJFord: It seems like this issue has been sorted out and might be ready to close. Thanks for your work keeping this repo tidy.

**Comment by OJFord** [comment]
Thanks!

@rehanguha, regarding promotions/multiple roles at the same company, see #297 for some other suggestions (or if you have any additional comments on it, let's keep it there) - I'm hoping to have a built-in mechanism for that soon.
