### ISSUE TITLE
Inactive commands

### ISSUE THREAD

**Issue by JustARandomGuy** [posquit0/Awesome-CV#4]
Hello,

I'm trying to use your template. Could you please tell me: 
1. Why are \quote and \position not appearing ?
2. If I don't use the social commands (homepage, github, linkedin), the pipes (separators) still appear; how do I get rid of them ?

**Comment by posquit0** [comment]
1. Sorry, it doesn't support that features yet, I'll add that ASAP.
2. I fixed it in the past, if you're using my Awesome CV in ShareLaTeX, that is not up-to-date. I'll contact to the staff of ShareLaTeX soon.

**Comment by posquit0** [comment]
Hello friend,

Now, I added position into header part, but I don't have any idea where is the best place for the quote. If you have any idea, please let me know :)

**Comment by JustARandomGuy** [comment]
Hello,

Thanks for the quick fix. A good place for the quote would be after the social information. Just like here : https://www.sharelatex.com/templates/cv-or-resume/moderncv-banking.

Thanks ;)

**Comment by posquit0** [comment]
I added the quote following the example of moderncv. Please check it out!

Thanks :+1:

**Comment by JustARandomGuy** [comment]
Excellent! Thanks a lot!
