### ISSUE TITLE
Section for highlights

### ISSUE THREAD

**Issue by hoangpham8182** [posquit0/Awesome-CV#40]
Hi,

Thanks a lot for a very nice template. I like it a lot. I am trying to create my own CV using your original version. I want to have a Highlights section under which only some lines with bullets should be added. I have tried to edit the class file but did not succeed. Could you please help?

Many thanks,
Hoang

**Comment by hoangpham8182** [comment]
I have found the solution from previous posts. 
Cheers,
Hoang

**Comment by posquit0** [comment]
That's glad to hear you solved already! Sorry for late check. These days, I'm spending so busy time...

Good luck!
