### ISSUE TITLE
Include bare LinkedIn & GitHub URL in the header section

### ISSUE THREAD

**Issue by JunjieLeiCoe** [posquit0/Awesome-CV#409]
Hi All, 

This is a truly awesome open source project! Thanks for all your effort!

What I'm actually want to know is how to include a bare address in the header section and also be clickable

For example, I know, for now you just need to include your GitHub Handler & LinkedIn Handler there. But when I include the full path `https://github.com/xxxxx` and `https://www.linkedin.com/in/xxxxx/`, it becomes not clickable and return a `404 page not found` error.

Does anyone has some suggestions on that!? Thanks in advance!

**Comment by dcsim** [comment]
Assuming you're putting the full path into the .tex file github...

Try changing line 509 in the .cls file from this
``` 
\href{https://github.com/\@github}{\faGithubSquare\acvHeaderIconSep\@github}%
```

to this

```
\href{\@github}{\faGithubSquare\acvHeaderIconSep\@github}%
```

It _should_ work. If it does, do the same for linkedin.

If you'd like to have a partial path on the resume, e.g. "github.com/UserName3384493942397," you would need to add the rest of the URL back into the .cls file, e.g. `\href{https://\@github}`

**Comment by OJFord** [comment]
We could potentially strip/avoid duplicating the prefix if present, but I'd be hesitant to do that without making it consistent behaviour across all of these header icon links, which would be quite a bit of work.

If you did want to take that on, I'd probably suggest refactoring them all to use some common `href` wrapper that does the stripping/de-duplicating. e.g. `\acvSocial{https://github.com/}{\faGithubSquare}{\@github}`.

**Comment by OJFord** [comment]
Ah, @dcsim points out in the issue linked above that that's been done (but could do with rebasing) in #315.

**Comment by JunjieLeiCoe** [comment]
Thanks all!!! for the help. 
Update -- changing Line 481 
```
        {%
          \ifbool{isstart}{\setbool{isstart}{false}}{\acvHeaderSocialSep}%
          \href{https://gitlab.com/\@gitlab}{\faGitlab\acvHeaderIconSep\@gitlab}% 
        }%
```

My line index might be off, remove the `https://gitlab.com/` will be fine`, just `@your peronsal handler` will do the job!
