### ISSUE TITLE
Package rerunfilecheck Warning: File `cv.out' has changed.

### ISSUE THREAD

**Issue by antenore** [posquit0/Awesome-CV#423]
This warning is printed  the first time we render the CV:

```
Package rerunfilecheck Warning: File `cv.out' has changed.
(rerunfilecheck)                Rerun to get outlines right
(rerunfilecheck)                or use package `bookmark'.
```

While it's just a warning, one is obliged to rerun xelatex, when the fix is very simple

If you want I can submit a PR

**Comment by OJFord** [comment]
Hm, yes, that is reproduced in CI too:
https://github.com/posquit0/Awesome-CV/runs/5468352192?check_suite_focus=true#step:4:488

PR certainly welcome, thanks!

**Comment by antenore** [comment]
Done, if you need more details let me know and thanks so much for this project!
