### ISSUE TITLE
Remove year and still keep cv vertically aligned

### ISSUE THREAD

**Issue by iCHAIT** [posquit0/Awesome-CV#43]
Hi, firstly I would like to thank you for creating such a neat and beautiful template. Now, my question is that is it possible to remove years from the **Program Committees** section and still keep the CV vertically aligned?

Example - 

Currently, if I remove years it looks like this -

### Program Committees

        Organizer & Co-director, 1st POSTECH Hackathon S.Korea
        Staff & Problem Writer, JFF(Just for Fun) Hacking Competition S.Korea

I want it to look like this - 

### Program Committees

`Organizer & Co-director, 1st POSTECH Hackathon S.Korea`
`Staff & Problem Writer, JFF(Just for Fun) Hacking Competition S.Korea`

I am sorry as this maybe a noob question as I have just started with latex, but it would be great if you could help :)

**Comment by johannesbottcher** [comment]
Put the following block before `\begin{document}`, play around with the values till you are satisfied.

```synta=latex
\renewenvironment{cvhonors}{%
  \vspace{\acvSectionContentTopSkip}
  \vspace{-2mm}
  \begin{center}
    \setlength\tabcolsep{0pt}
    \setlength{\extrarowheight}{0pt}
    \begin{tabular*}{\textwidth}{L{\textwidth - 4.0cm} R{2.5cm}}
}{%
    \end{tabular*}
  \end{center}
}
\renewcommand*{\cvhonor}[4]{%
  \honorpositionstyle{#1}, \honortitlestyle{#2} & \honorlocationstyle{#3} \\
}
```

**Comment by iCHAIT** [comment]
Thanks a lot @johannesbottcher , works for me :)

**Comment by iCHAIT** [comment]
@johannesbottcher  HI, I have a question regarding this same issue.

I want the following (the Program Committees Section) -

```
2013    Organizer & Co-director, 1st POSTECH Hackathon S.Korea                                S.Korea
2012    Staff & Problem Writer, JFF(Just for Fun) Hacking Competition S.Korea                 S.Korea
```

To look like this - 

```
Organizer & Co-director, 1st POSTECH Hackathon S.Korea                                        S.Korea
Staff & Problem Writer, JFF(Just for Fun) Hacking Competition S.Korea                         S.Korea
```

The snippet you wrote works fine if I just want the middle content, but if I want to keep the middle content as well as the content on the right hand side (`S.Korea` in this case) the right content gets displaced to left hand side on account of removing the year. Is it possible to stop the content on the right getting displaced to the left?
I hope my question is clear, let me know if you want me to elaborate more on it :)

**Comment by johannesbottcher** [comment]
@iCHAIT Quoting myself from three weeks back:
>Put the following block before \begin{document}, **play around with the values till you are satisfied**.

Highlight added just now.
