### ISSUE TITLE
Long github names break

### ISSUE THREAD

**Issue by khinshankhan** [posquit0/Awesome-CV#435]
**Issue:**
When using my full github name (`khinshankhan`), I get this error:
![image](https://user-images.githubusercontent.com/22206867/176305311-60856ea2-76aa-42ef-bb1d-3f4a97ad2e57.png)

This doesn't seem to be an issue with the number of characters in the header (it was working if i put my github name as `k`, and since my linkedin is the same as github, I tried swapping them and still got the error).

**Potential Fix**:
I'm not wholly familiar with latex, but I think this line is the culprit https://github.com/posquit0/Awesome-CV/blob/5b05d935658377c73a3456269d23a276b19804f7/awesome-cv.cls#L495

Looking at the linkedin logic, I replaced the line with
```latex
\href{https://github.com/\@github}{\faGithubSquare\acvHeaderIconSep{\expandafter\ul\expandafter{\@github}}}%
```
and it works like a charm. Wonder if this should be merged in if it's 'proper'.

**Comment by OJFord** [comment]
Thanks! Could you submit as a PR?

**Comment by khinshankhan** [comment]
Hello, I updated to the latest awesome cv and this fix is no longer needed. Unless someone else comes along with the same issue, I think we can safely close this. Thanks for your hard work :+1:
