### ISSUE TITLE
Add Computer Skills

### ISSUE THREAD

**Issue by billlipeng** [posquit0/Awesome-CV#44]
I am a software engineer and I'd like to add a section for Computer Skills. The problem is that I have no idea about layout(UI) of these skills. Could you please shed some light on it?

This is a single example to show the content I'd like to add. 
` {\bf Prog. Language:} C++, Java, Python, MIPS, SystemC\\
  {\bf Prog. Environment:} gcc, Eclipse, Visual Studio, Xcode, Android Developer Tools\\
  {\bf OS :} Unix, Windows  \hspace{7mm}  {\bf Version Control:} Git
	\hspace{7mm} {\bf Text Editor:} vi, LaTex `

Thanks for the awesome CV template!

**Comment by johannesbottcher** [comment]
Where is that code from? It uses commads that are obsolete for 20 years.

Can you provide a minimal working example of what you have so far? Just a snippet isn't very helpful.

**Comment by billlipeng** [comment]
Thanks for your concern. I have found the answer.
