### ISSUE TITLE
alignment of skills is not correct

### ISSUE THREAD

**Issue by kanishkaverma** [posquit0/Awesome-CV#444]
Hey, 
I just had a quick question as to how I can fix the alignment of some of the skills. It currently looks like this : 

![Screenshot from 2022-11-03 19-44-10](https://user-images.githubusercontent.com/58015272/199873933-d1e9ad39-c18c-436a-bf0a-bdfb0df8874e.png)

and I would like the skill headers to be properly left aligned. 
This is what my correct awesome-cv.cls looks like: 

```


% Define an environment for cvskill
\newenvironment{cvskills}{%
	\vspace{\acvSectionContentTopSkip}
	\vspace{-2.0mm}
	\begin{center}
		\setlength\tabcolsep{1ex}
		\setlength{\extrarowheight}{0pt}
		\begin{tabular*}{\textwidth}{@{\extracolsep{\fill}} r L{\textwidth * \real{0.9}}}
			}{%
		\end{tabular*}
	\end{center}
}
% Define a line of cv information(skill)
% Usage: \cvskill{<type>}{<skillset>}
\newcommand*{\cvskill}[2]{%
	\skilltypestyle{#1} & \skillsetstyle{#2} \\
}




```

Thank you so much for your help. 
warmest regards, 
Kanishka

**Comment by oskarryn** [comment]
Hi,

Left-alignment of "skilltypestyle" (1st column in cvskills) can be achieved by simply changing `r  L` to `l L` in the table spec in cvskills env.

Unless you meant something different?

**Comment by OJFord** [comment]
It's not clear to me what the problem is here, but if the snippet you posted addresses something you think should need fixed please open a PR.
