### ISSUE TITLE
Embed links in text

### ISSUE THREAD

**Issue by amtrivedi91** [posquit0/Awesome-CV#45]
Under the Writing Section how do I link the `Facebook Page` written in red to an actual facebook page?

**Comment by johannesbottcher** [comment]
With package `hyperref`, which is already loaded by the class. By default, links are hidden, though.

**Comment by amtrivedi91** [comment]
Thanks for your response @johannesbottcher , can you give a quick example?

**Comment by johannesbottcher** [comment]
Ugly but quick: `{\color{red}\href{https://github.com/posquit0/Awesome-CV/issues/45}{This is not Facebook}}`

**Comment by amtrivedi91** [comment]
Thanks a lot @johannesbottcher  works for me :)
