### ISSUE TITLE
Downloading and using the zip on Windows can result in error

### ISSUE THREAD

**Issue by UweZiegenhagen** [posquit0/Awesome-CV#483]
I downloaded the ZIP of the repository and was informed by 7zip during the extraction of the files that one symbolic link could not be created. The files in the examples folder did not work at all, I finally found out, that the class file in the examples folder was this symbolic link. Since 7zip could not resolve the symlink, the class file in the examples folder was just 0 Bytes. Maybe it is a good idea to get rid of the symlink and use a copy of the file instead.

**Comment by OJFord** [comment]
There's not really any reason to download a zip of the repository?

If you want to use AwesomeCV for your own CV, you just need [awesome-cv.cls](https://github.com/posquit0/Awesome-CV/blob/master/awesome-cv.cls).

If you want to contribute to the project, you need to `git clone` the repo, which.. I would _assume_ can handle symlinks even on Windows, but you probably should use WSL anyway.
