### ISSUE TITLE
Can't edit some sessions

### ISSUE THREAD

**Issue by cblanche809** [posquit0/Awesome-CV#484]
Hello,
When I make a change to " it's not reflected after i click recompile. I'm new to LaTeX so I'm probably missing something simple. 
I get the following error
![image](https://github.com/posquit0/Awesome-CV/assets/118459086/6cf12e71-e672-411f-a125-910c21ed4758)

Thanks.

**Comment by ycli0536** [comment]
Have you changed your compiler to XeLaTex or LuaLaTex? [Change Compiler on Overleaf].(https://www.overleaf.com/learn/how-to/Changing_compiler)
