### ISSUE TITLE
Font not found when \fontdir and Path=\@fontdir present

### ISSUE THREAD

**Issue by dwsmith1983** [posquit0/Awesome-CV#49]
I tried using the \fontdir command with the correct paths but every time I compiled, I was told font not found.

I solved this by commenting out \fontdir and all Path=\@fontdir in the style and class file. If the users install the fonts in the normal system path for fonts, these lines of code aren't needed and cause problems on compile.

**Comment by haojunsui** [comment]
You can use the template from https://www.sharelatex.com/templates/cv-or-resume/awesome-cv. They fixed this issue.

**Comment by cviebig** [comment]
I did experience the same issue when using `xelatex` but could avoid it by using `lualatex`.

**Comment by ooker777** [comment]
None of the solution works for me. I use Windows 10, MiKTeX.

**Comment by alex1a** [comment]
same here, Windows 10 latest update, MiKTeX all updated with CMD terminal
