### ISSUE TITLE
Overflow cventries when compiled with newest tex-live; bullet bugs

### ISSUE THREAD

**Issue by neronguyenvn** [posquit0/Awesome-CV#528]
Anyone has same issues with me, I no idea but follow the examples and now it has bug I couldn't do anything ...

![image](https://github.com/posquit0/Awesome-CV/assets/50225603/4c163e69-4652-4f19-9b2c-7d79ab70253e)

**Comment by neronguyenvn** [comment]
My xelatex current version:

 xelatex
This is XeTeX, Version 3.141592653-2.6-0.999996 (TeX Live 2024) (preloaded format=xelatex)
 restricted \write18 enabled.
**

**Comment by dcsim** [comment]
`XeTeX 3.141592653-2.6-0.999996` builds the example files without issue for me. Is it failing on the example files or files you've edited?

**Comment by neronguyenvn** [comment]
I just clone and build the example files. So some error with my tex live full right ?

**Comment by neronguyenvn** [comment]
I just reinstall entire os and texlive-full but nothing changes ...

**Comment by neronguyenvn** [comment]
@dcsim can you do a favor build the file for me when I done please; thank you ...

**Comment by neronguyenvn** [comment]
ok first maybe I gonna install again with apt
