### ISSUE TITLE
Switch language

### ISSUE THREAD

**Issue by sbmueller** [posquit0/Awesome-CV#53]
I tried to change to german with `\usepackage[ngerman]{babel}`, but suddenly I get an error:
```
./cv-sections/education.tex:44: Argument of \language@active@arg" has an extra }. [}]
./cv-sections/education.tex:44: Paragraph ended before \language@active@arg" was complete. [}]
./cv-sections/education.tex:44: Missing } inserted. [}]
./cv-sections/education.tex:44: Extra }, or forgotten $. [}]
```
When I use `\usepackage[english]{babel}` it works fine. Mentioned source line is:
```
\cventry
{abcd} % Degree
{abcd} % Institution
{abcd % Location
{abcd} % Date(s)
{ % Description(s) bullet points
} % THIS LINE THROWS ERROR
```

**Comment by posquit0** [comment]
Hmmm...
Try to change font which support German.

**Comment by sbmueller** [comment]
@posquit0 thanks for the answer. I'm not sure what you mean by that. Since I didn't change any content, the fonts should work after selecting [ngerman]{babel}, shouldn't it? There are no additional special characters or similar.

**Comment by johannesbottcher** [comment]
As far as i can tell, there is neither a folder cv-sections, nor a line 44 in the example given in this repository. Please provide a minimal working example, along with the details of your LaTeX installation.

Since i don't consider this to be a problem of this template, it would be better to ask the question at goLaTeX or a similar place.

**Comment by sbmueller** [comment]
@johannesbottcher Oops, sorry. I got the template from http://www.latextemplates.com/template/awesome-resume-cv. There, the structure is slightly different.

I have managed to fix this error by rewriting the `education.tex`, so it seems there was a bad unicode character or similar. Thanks for the quick help!

**Comment by johannesbottcher** [comment]
@sbmueller I am a bit confused, as there is a link on that website *ask a question* where you are redirected to latex-community.org. Apparently, that button is too small.
