### ISSUE TITLE
Support on LC

### ISSUE THREAD

**Issue by johannesbottcher** [posquit0/Awesome-CV#6]
Hi there, i don't have time to look into this myself.

http://latex-community.org/forum/viewtopic.php?f=45&t=26933&p=92672#p92672

By the way, the license of the repo is MIT, the class file is copyrighted to you. You may wanna loose a word about that to the OP.

**Comment by posquit0** [comment]
I cannot understand abbreviations in your message.
What is LC and OP?

Is there any problem cuz of MIT License and my copyright? I need more explanations!

**Comment by johannesbottcher** [comment]
LC => Latex community
OP => original poster


You might want to add an explicit license info into the files. Alltough, personally, i think that MIT and other very open licenses aren't the best choice, as explained in my two opening comments in https://github.com/VelNZ/mastersdoctoralthesislatex/issues/6

**Comment by posquit0** [comment]
Thanks for your kindness. I changed a License type by your suggestion! LPPL for class file, CC for LaTeX template.

Thanks!

**Comment by hacksalot** [comment]
Hi guys,

I concur that MIT is not always the most appropriate choice but [CC BY-NC-SA](https://creativecommons.org/licenses/by-nc-sa/3.0/) for the resume template seems a little restrictive given that:

- Awesome-CV is itself a derivative work of FancyCV
- Awesome-CV is used in a [couple commercial spots already](https://www.sharelatex.com/templates/cv-or-resume/awesome-cv).
- LPPL explicitly allows commercial use.

Is there any reason not to use LPPL across the board or go with [CC BY SA](https://creativecommons.org/licenses/by-sa/4.0/), preserving attribution but allowing for commercial use?

Thanks!

**Comment by posquit0** [comment]
Hi, I agree with your opinion, sorry for my lack of understanding about LICENSE. I changed License type for LaTeX template from CC BY-NC-SA to CC BY-SA.

Thanks to all of you !

**Comment by hacksalot** [comment]
Thanks @posquit0! -- this project has re-sparked my interest in LaTeX and it's been fun.
