### ISSUE TITLE
HTML output?

### ISSUE THREAD

**Issue by bvosk** [posquit0/Awesome-CV#62]
I'm pretty new to LaTeX and I was wondering if there's an easy way to compile this to HTML rather than a PDF?  I would love to be able to throw my resume up on my website from the same source as the PDF.

**Comment by johannesbottcher** [comment]
`tex4ht` is a good tool for that, but it is limited. How good it works with this template ... i have no idea.

**Comment by bvosk** [comment]
Ok thanks for the response and thanks for the awesome template in the first place! I'll take a look at that and report my findings back here.

**Comment by mattcristal** [comment]
I was wondering if anyone had some luck here, I tried with `tex4ht` but the results were not great, main issues are custom fonts and icons
