### ISSUE TITLE
What should I do if I want GPA inlined with Location and Dates?

### ISSUE THREAD

**Issue by anirtek** [posquit0/Awesome-CV#66]
\cventry
    {B.S. in Computer Science and Engineering} % Degree
    {POSTECH(Pohang University of Science and Technology)} % Institution
    {Pohang, S.Korea} % Location
    {Mar. 2010 - PRESENT} % Date(s)
    {
      \begin{cvitems} % Description(s) bullet points
        \item {Got a Chun Shin-Il Scholarship which is given to promising students in CSE Dept.}
      \end{cvitems}
    }

This gets organized in a format where University, Degree and Bulleted Point gets organized below each other after one another. And Location, Dates are exactly opposite of first two points. I want to add GPA at the end of Bulleted Point and I want to organize it exactly below Location and Dates. What should I do for this?

**Comment by johannesbottcher** [comment]
The template, as any other template, defines the style. If you want a different style, you need to do some heavy patching, or ... use another template.
