### ISSUE TITLE
Texlive package?

### ISSUE THREAD

**Issue by lunaryorn** [posquit0/Awesome-CV#67]
Is there a package that I can install through texlive manager? Or do I need to fork the repository in order to use it?

**Comment by johannesbottcher** [comment]
No, pleas do *NOT* fork the repo.  Use the download button.
![downloadawesomecv](https://cloud.githubusercontent.com/assets/8258702/18230479/c2f6fef0-729c-11e6-9878-a83e44722f4e.png)

**Comment by lunaryorn** [comment]
@johannesbottcher I appreciate your comment but I am afraid it fails to address my question which was about whether there are packages available for installation through texlive manager.

Whether I fork the repository is my choice—and mine alone.  I find that in the absence of proper packages forking supports my workflow best and provides the easiest option to follow upstream's updates, and I do not think that I must change my workflow just to bring down a number on the website of this repository.

**Comment by johannesbottcher** [comment]
No. There are no packages for TeX Live as thetemplate has not beenuploaded to CTAN. 

Updates of LaTeX templates are almost always *not* backwards compatible. I strongly advise against making template updates while working on a project.

**Comment by lunaryorn** [comment]
Are there plans to publish this class to CTAN?

@johannesbottcher I appreciate your advice, but you may safely leave concerns of backwards compatibility to me.  Rest assured that I know what I'm doing.

**Comment by justinbass** [comment]
Doesn't look like there are any future plans to publish this.

**Comment by hyiltiz** [comment]
@lunaryorn Did you plan to work on uploading a CTAN package?
