### ISSUE TITLE
Summary.tex does not compile

### ISSUE THREAD

**Issue by Gknoblau** [posquit0/Awesome-CV#72]
https://github.com/posquit0/Awesome-CV/blob/master/examples/resume/summary.tex

Error Message: paragraph ended before /paragraphstyle was completed <to be read again>

Any help would be greatly appreciated!

**Comment by johannesbottcher** [comment]
You most likely have an error in your code. hard to tell, i cannot see it.  Please provide a minimal working example.

**Comment by posquit0** [comment]
Close this issue because he doesn't give any more informations for his problem.
