### ISSUE TITLE
Is another cover letter type public?

### ISSUE THREAD

**Issue by yuchenglin** [posquit0/Awesome-CV#73]
Hi,
I saw in README that there are two kind of cover letter types. However, when I read the code, I only found one type. Is [another cover letter](https://raw.githubusercontent.com/posquit0/Awesome-CV/master/examples/coverletter-0.png) public here? Thanks

**Comment by johannesbottcher** [comment]
I can see only one style. Can you be more specific?

**Comment by posquit0** [comment]
Oh, I just attached 2 example cover letters, however, they're written 
with exactly same template code.
Only difference is an example content.


2016. 10. 6. 오전 11:30에 Johannes Böttcher 이(가) 쓴 글:

**Comment by yuchenglin** [comment]
I see. Thanks!
