### ISSUE TITLE
Order of links in personal data section.

### ISSUE THREAD

**Issue by topless** [posquit0/Awesome-CV#76]
I am looking for a way to customise the order that personal data appear under my name.
So what I am actually looking for is a way to swap places my `linkedin` with my `github` link.

Reordering in my `resume.tex` the commands `\linkedin{my_hanlde}` and `\github{my_handle}` didn't seem to affect they order they display.

Thanks.

**Comment by johannesbottcher** [comment]
The order of elements is defined by the class file.  If you want to change the order, you have to edit the lass file yourself. Please do so according to the license of this project and the class file.

See also https://github.com/posquit0/Awesome-CV/pull/69

**Comment by topless** [comment]
It depends on the order of `ifthenelse` commands, I was changing other stuff, thanks for the hint :) great work by the way!
