### ISSUE TITLE
How to change the address in the italics to regular and also the place and date on the right had side of the document?

### ISSUE THREAD

**Issue by anirtek** [posquit0/Awesome-CV#77]

**Comment by johannesbottcher** [comment]
`\renewcommand*{\headeraddressstyle}[1]{{\fontsize{8pt}{1em}\headerfont\color{lighttext} #1}}`

`\renewcommand*{\letterdatestyle}[1]{{\fontsize{9pt}{1em}\bodyfontlight\color{graytext} #1}}`

**Comment by Masshat** [comment]
It would be really appreciated also if the guy stop opening issues according to his own problem, this is a template example, if you want to change it go deeper in the code and try to understand how the graphics and the fonts are madded.
