### ISSUE TITLE
Publications section

### ISSUE THREAD

**Issue by gpetrousov** [posquit0/Awesome-CV#81]
Would have been nice to have a section for publications as well.

Great template.

**Comment by johannesbottcher** [comment]
Please have a look at https://github.com/posquit0/Awesome-CV/issues/38

**Comment by gpetrousov** [comment]
So it's an open issue.
Thanks.
I used
\cvsection{Publications}
\begingroup
\renewcommand{\section}[2]{}%
\bibliographystyle{unsrt}
\bibliography{refs}
\nocite{*}
