### ISSUE TITLE
How to use special characters (spanish)

### ISSUE THREAD

**Issue by LuisLauM** [posquit0/Awesome-CV#88]
Hello

I would like to know how I can use special characters (used in spanish, like accents). I have been looking for in forums, but I still has problems.

Thank you.

**Comment by johannesbottcher** [comment]
Why? It should work. Can you prepare a minimum working example, so we can reproduce your troubles?

**Comment by LuisLauM** [comment]
Well, I'm just trying to compile and build using characters as á, é, í, ó, ú, ñ and I'm receiving strange symbols: like this (X).

**Comment by LuisLauM** [comment]
I have to make some changes in the position of files so as to make functional on my PC. Yes, it admits special characters, but I have to install the fonts manually. I use Windows 10, 64  bits. Thanks, good template!
