### ISSUE TITLE
Add summary section

### ISSUE THREAD

**Issue by k1-hedayati** [posquit0/Awesome-CV#91]
Having a summary section like LinkedIn to summarize personal expertise and interests and other info is helpful for recruiters to get better idea of what kind of person they are recruiting.

**Comment by posquit0** [comment]
Already implemented feature.

**Comment by k1-hedayati** [comment]
Ok, here is my summery.tex
```tex
\cvsection{Summary}

\begin{cvparagraph}
Your Summary
\end{cvparagraph}
```
When I try to complie it I get this error
```
Argument of \@sectioncolor has an extra }.
<inserted text> 
                \par 
l.4 Y
     our Summary 
```

**Comment by k1-hedayati** [comment]
@posquit0 would you like to help me with this issue?

**Comment by k1-hedayati** [comment]
Fixed, I had old version
Thanks

**Comment by k1-hedayati** [comment]
I was using an old version

**Comment by dmjio** [comment]
@ghost how did you update your version? How did you check that it was old?
