### ISSUE TITLE
Add list of professional references

### ISSUE THREAD

**Issue by thiagoveloso** [posquit0/Awesome-CV#94]
This CV is literally awesome, very close to perfection (at least for my needs).

To make it even better, could anyone help me add a list of professional references by the end of the CV? 

I've found a discussion with a potential solution here: (http://tex.stackexchange.com/questions/34881/references-section-in-a-cv). But adapting it to this Awesome-CV template is far beyond my (basic) Latex skills.

Can anyone more proficient give a little hand?

Thank you in advance!

**Comment by johannesbottcher** [comment]
[Crosspost](http://tex.stackexchange.com/questions/347495/list-of-professional-references-in-awesome-cv)

**Comment by thiagoveloso** [comment]
Managed to solve by following this: https://www.overleaf.com/latex/templates/awesome-cv/tvmzpvdjfqxp#comment-2563071701

**Comment by Miail** [comment]
Could you provide with the solution here.. The link doesn't seem to show the comment discussing the topic.

**Comment by bibbca** [comment]
Linked comment no longer exists.  Please reopen issue.

**Comment by aklife97** [comment]
The following code snippet is the modified version of stack exchange code to work with Awesome CV

`\cvsection{References}

\newcommand{\cvdoublecolumn}[2]{%
    \begin{minipage}[t]{{.45\linewidth}}#1\end{minipage}%
    \hfill%
    \begin{minipage}[t]{{.45\linewidth}}#2\end{minipage}%
}

\newcommand{\cvreference}[7]{%
    \textbf{#1}\newline% Name
    \ifthenelse{\equal{#2}{}}{}{#2\newline}%
    \ifthenelse{\equal{#3}{}}{}{#3\newline}%
    \ifthenelse{\equal{#4}{}}{}{#4\newline}%
    \ifthenelse{\equal{#5}{}}{}{#5\newline}%
    \ifthenelse{\equal{#6}{}}{}{\faEnvelope\acvHeaderIconSep~\texttt{#6}\newline}%
    \ifthenelse{\equal{#7}{}}{}{#7}}

\cvdoublecolumn{\cvreference{Nicolai Reshetikhin}
    {Department of Mathematics}
    {University of California}
    {Berkeley, CA 94720-3840}
    {}
    {reshetik@math.berkeley.edu}
    {510-643-6234}%
    }
    {\cvreference{Mikhail Khovanov}
    {Department of Mathematics}
    {Columbia University}
    {990 Broadway}
    {New York, NY 10027}
    {khovanov@columbia.edu}
    {212-854-4186}%
    }`

**Comment by tdelhomme** [comment]
@aklife97 thanks for the code, that's perfect!

**Comment by mbuet2ner** [comment]
Building on top of the code snippet by @aklife97 , I made a few modifications to closer align the looks with the template:

`\cvdoublecolumn{\cvreference{Best reference}
	{Department of Superiority}
	{University of the Universe}
	{}
	{Address 42, 4242}
	{mail@mail.mail}
	{1337}%
}
{\cvreference{Best reference}
	{Department of Superiority}
	{University of the Universe}
	{}
	{Address 42, 4242}
	{mail@mail.mail}
	{1337}%
}`

**Comment by mbuet2ner** [comment]
Building on top of @aklife97 code snippet, I added a few modifications to closer align the style with the template.

- added missing icons
- fixed bold name (solution is somewhat hacky)
- use font configuration consistent with the rest of the template

```
\cvsection{References}

\newcommand{\cvdoublecolumn}[2]{%
	\begin{minipage}[t]{{.45\linewidth}}#1\end{minipage}%
	\hfill%
	\begin{minipage}[t]{{.45\linewidth}}#2\end{minipage}%
}

\newcommand{\cvreference}[7]{%
	\entrytitlestyle{#1}\newline% Name
	\ifthenelse{\equal{#2}{}}{}{#2\newline}%
	\ifthenelse{\equal{#3}{}}{}{#3\newline}%
	\ifthenelse{\equal{#4}{}}{}{#4\newline}%
	\ifthenelse{\equal{#5}{}}{}{\faHome\acvHeaderIconSep~#5\newline}%
	\ifthenelse{\equal{#6}{}}{}{\href{mailto:#6}{\faEnvelope\acvHeaderIconSep~#6\newline}}%
	\ifthenelse{\equal{#7}{}}{}{\faMobile\acvHeaderIconSep~#7\newline}}

\cvdoublecolumn{\cvreference{Best reference}
	{Department of Superiority}
	{University of the Universe}
	{}
	{Address 42, 4242}
	{mail@mail.mail}
	{1337}%
}
{\cvreference{Best reference}
	{Department of Superiority}
	{University of the Universe}
	{}
	{Address 42, 4242}
	{mail@mail.mail}
	{1337}%
}
```
**Result:**
![grafik](https://user-images.githubusercontent.com/20720363/83797575-2c387900-a6a3-11ea-9a8d-16801cfc5817.png)

**Comment by StefanVeleski** [comment]
@mbuet2ner That's great! Is there any way to decrease the size of the font though? The built in font size macros (\footnotesize, \tiny, \small etc.) don't work within the template.

**Comment by mbuet2ner** [comment]
@StefanVeleski glad you like it. I have no idea to be honest. Maybe check for some predefined text snippet in the class file?

**Comment by sanjay032** [comment]
> 
> 
> The following code snippet is the modified version of stack exchange code to work with Awesome CV
> 
> ```
> \cvsection{References}
> 
> \newcommand{\cvdoublecolumn}[2]{%
>     \begin{minipage}[t]{{.45\linewidth}}#1\end{minipage}%
>     \hfill%
>     \begin{minipage}[t]{{.45\linewidth}}#2\end{minipage}%
> }
> 
> \newcommand{\cvreference}[7]{%
>     \textbf{#1}\newline% Name
>     \ifthenelse{\equal{#2}{}}{}{#2\newline}%
>     \ifthenelse{\equal{#3}{}}{}{#3\newline}%
>     \ifthenelse{\equal{#4}{}}{}{#4\newline}%
>     \ifthenelse{\equal{#5}{}}{}{#5\newline}%
>     \ifthenelse{\equal{#6}{}}{}{\faEnvelope\acvHeaderIconSep~\texttt{#6}\newline}%
>     \ifthenelse{\equal{#7}{}}{}{#7}}
> 
> \cvdoublecolumn{\cvreference{Nicolai Reshetikhin}
>     {Department of Mathematics}
>     {University of California}
>     {Berkeley, CA 94720-3840}
>     {}
>     {reshetik@math.berkeley.edu}
>     {510-643-6234}%
>     }
>     {\cvreference{Mikhail Khovanov}
>     {Department of Mathematics}
>     {Columbia University}
>     {990 Broadway}
>     {New York, NY 10027}
>     {khovanov@columbia.edu}
>     {212-854-4186}%
>     }
> ```

love it. Thanks

**Comment by VladimirSiv** [comment]
@StefanVeleski To change the style you can use predefined styles:
https://github.com/posquit0/Awesome-CV/blob/4be6c213c8631a1fd68d1ad452e88b722b911f78/awesome-cv.cls#L186-L200

or you can define your own.

Here's an example:

```
\cvsection{References}

\newcommand*{\emaillink}[1]{{\fontsize{8pt}{1em}\bodyfont\scshape\color{awesome} #1}}

\newcommand{\cvdoublecolumn}[2]{%
	\begin{minipage}[t]{{.45\linewidth}}#1\end{minipage}%
	\hfill%
	\begin{minipage}[t]{{.45\linewidth}}#2\end{minipage}%
}

\newcommand{\cvreference}[5]{
	\entrytitlestyle{#1}\newline
	\descriptionstyle{#2}\newline
	\descriptionstyle{#3}\newline
	\faHome\acvHeaderIconSep~\descriptionstyle{#4}\newline
	\href{mailto:#5}{\faEnvelope\acvHeaderIconSep~\emaillink{#5}\newline}}

\cvdoublecolumn{\cvreference{Best reference}
	{Department of Superiority}
	{University of the Universe}
	{Address 42, 4242}
	{mail@mail.mail}
}
{\cvreference{Best reference}
	{Department of Superiority}
	{University of the Universe}
	{Address 42, 4242}
	{mail@mail.mail}
}
```
I hope this helps.
